### ISSUE TITLE
Code immediately stop when training starts

### ISSUE THREAD

**Issue by lxy598951** [tianzhi0549/FCOS#100]
I use coco 2017 to test if code can start normally. But when Strat training, the code immediately stop. How could I solve this?

Follows are last line of log file.
> 2019-07-25 15:28:44,686 maskrcnn_benchmark.trainer INFO: Start training
> 2019-07-25 15:28:44,816 maskrcnn_benchmark.trainer INFO: Total training time: 0:00:00.128995 (0.0000 s / it)

**Comment by lxy598951** [comment]
@chhshen Could you tell me why you closed my issue?

**Comment by tianzhi0549** [comment]
It might be because you already have checkpoints in your directory.
