### ISSUE TITLE
FCOS_syncbn_bs32_c128_MNV2_FPN_1x model size

### ISSUE THREAD

**Issue by Tim5Tang** [tianzhi0549/FCOS#107]
i found that the FCOS_syncbn_bs32_c128_MNV2_FPN_1x model you released is 15Mb, but i use your FCOS_syncbn_bs32_c128_MNV2_FPN_1x config to test, the model nearly 30Mb, is there some other config need to set ?

**Comment by tianzhi0549** [comment]
@Tim5Tang Please be aware that we only remove all solver states in our released models. Please refer to https://github.com/tianzhi0549/FCOS/issues/35#issuecomment-492555271.

**Comment by Tim5Tang** [comment]
ok,thanks
