### ISSUE TITLE
comparison of inference time to Faster R-CNN

### ISSUE THREAD

**Issue by stigma0617** [tianzhi0549/FCOS#108]
Hi,

I measured inference time and compare with [Faster R-CNN](https://github.com/facebookresearch/maskrcnn-benchmark) on Titan Xp

CUDA v9.0
pytorch 1.1.0

| meta-arch. | backbone | AP(minival) |inf. time(ms) |
|:---:|:---:|:---:|:---:| 
| Faster R-CNN | R-50 | 36.8| 78 |
| FCOS | R-50 | 37.1| 98 |

Why anchor-free FCOS is slower than anchor-based Faster R-CNN ??

Have you profiled which component is time bottleneck?

**Comment by tianzhi0549** [comment]
@stigma0617 Is this time the averaged time on a benchmark such as COCO?

The inference time of two-stage detectors largely depends on the number of proposals. The number of proposals may significantly vary between different images.

**Comment by stigma0617** [comment]
@tianzhi0549,

Yes, this results is on COCO minival(5000 images).

Faster R-CNN result is based on default setting without any bells-and-whistles.

**Comment by stigma0617** [comment]
@tianzhi0549,

Have you compared with RetinaNet-R-50-FPN?

**Comment by tianzhi0549** [comment]
@stigma0617 It seems you did not load weights of Faster R-CNN. I did not test the inference time of RetinaNet-R-50. But by design, it is impossible that FCOS is slower than RetinaNet.

**Comment by stigma0617** [comment]
@tianzhi0549 

> It seems you did not load weights of Faster R-CNN.

No. I already load the weight file using 'last_checkpoint' file.

**Comment by bearcatt** [comment]
@stigma0617  The head module in FCOS (or RetinaNet) is very time-consuming (about100 GFLOPS for an 800x1200 image) since it operates on **8x** to128x downsampled feature maps. In contrast, the ROIHead module of FasterRCNN-FPN operates on 7x7 feature maps due to ROIPooling. 

The inference time of FasterRCNN-FPN and RetinaNet can be found in Detectron's Model Zoo.

**Comment by stigma0617** [comment]
@bearcatt ,

Inference time is different according to GPU, pytorch version, CUDA, etc. 

So when it comes to comparing with different architecture, it should be tested on a same environment. 

However, the results of Detectron's Model Zoo are old and are not keeped track of.  

Then, I tested and compared FCOS with Faster R-CNN on my same GPU environment.

But my results are weird as above the table and wonder why FCOS is slower than Faster R-CNN and ask whether authors compare FCOS with Faster R-CNN and RetinaNet.

**Comment by bearcatt** [comment]
@stigma0617 I mean that in the Detectron Model Zoo, FasterRCNN-FPN-50 is faster than RetinaNet-R-50 with the same settings (GPU, pytorch version, CUDA, etc.). So, FCOS is slower than FasterRCNN it is not that weird.

**Comment by tianzhi0549** [comment]
@stigma0617 @bearcatt I quoted the inference time from https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md. But that time seems not to be measured correctly.

I don't have Titan XP, so I run some tests on 1 1080Ti GPUs. The results are as follow.

**Faster R-CNN:**
```
python tools/test_net.py \
    --config-file configs/e2e_faster_rcnn_R_50_FPN_1x.yaml \
    MODEL.WEIGHT e2e_faster_rcnn_R_50_FPN_1x.pth \
    TEST.IMS_PER_BATCH 1 \
    MODEL.FCOS_ON False
```
Results:
```
2019-08-05 19:09:43,580 maskrcnn_benchmark.inference INFO: Total run time: 0:07:34.494380 (0.0908988759995 s / img per device, on 1 devices)
2019-08-05 19:09:43,581 maskrcnn_benchmark.inference INFO: Model inference time: 0:06:57.629121 (0.0835258241177 s / img per device, on 1 devices)
```

**FCOS:**
```
python tools/test_net.py \
    --config-file configs/fcos/fcos_R_50_FPN_1x.yaml \
    MODEL.WEIGHT FCOS_R_50_FPN_1x.pth \
    TEST.IMS_PER_BATCH 1
```
Results:
```
2019-08-05 17:10:00,975 maskrcnn_benchmark.inference INFO: Total run time: 0:07:44.444358 (0.0928888715744 s / img per device, on 1 devices)
2019-08-05 17:10:00,975 maskrcnn_benchmark.inference INFO: Model inference time: 0:07:05.434989 (0.0850869977474 s / img per device, on 1 devices)
```

**Conclusion:**
Overall, on my side with 1080Ti GPUs, FCOS has a similar speed to Faster R-CNN. But the claim "much faster" is wrong. Thank you very much for pointing it out. I will change it. Thankfully, we do not have the claim in our paper:-).

**Comment by stigma0617** [comment]
@tianzhi0549 Thanks for your sincerely reply. 

I really like your FCOS and hope future works for FCOS will be faster soon. 

I have tried to improve FCOS with my backbone networks, too.

Good luck :)

**Comment by stigma0617** [comment]
@tianzhi0549, May I ask one more question?

With same min resolution 800, which part(or module) is time bottleneck you think?

**Comment by tianzhi0549** [comment]
@stigma0617 As mentioned by @bearcatt, it should be the head towers. https://github.com/tianzhi0549/FCOS/blob/a9ce4ccdf47b147973f33e3b3cd29d45fc6b77ab/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py#L24

**Comment by stigma0617** [comment]
@tianzhi0549 thanks 👍
