### ISSUE TITLE
ImportError: cannot import name 'is_pytorch_1_1_0_or_later'

### ISSUE THREAD

**Issue by SkeletonOne** [tianzhi0549/FCOS#109]
All other imports are successful, only this one raises error. Besides, if I delete the line of code of importing this function, it raises another error: KeyError: 'Non-existent config key: MODEL.FCOS_ON'

Besides, my env is pytorch1.1.0 + torchvision0.2.1

**Comment by tianzhi0549** [comment]
@SkeletonOne Please run "python setup.py build develop" to install FCOS again.

**Comment by SkeletonOne** [comment]
@tianzhi0549 Sadly it still raises the same error... And I also tried created a new conda env and re-clone your git and build... But still the same problem :(

**Comment by tianzhi0549** [comment]
@SkeletonOne Please run `python -c "import maskrcnn_benchmark; print(maskrcnn_benchmark)"` to see if you are importing the module from a correct location.

**Comment by SkeletonOne** [comment]
@tianzhi0549 The location is correct...However it seems that I found out why the problem occurs, this work differs from maskrcnn-benchmark is that it does not support apex... I'm trying to change my conda env and have a try, and once it solved I'll close this issue :)

**Comment by tianzhi0549** [comment]
@SkeletonOne Did you run that command line outside the root directory of this project?

**Comment by SkeletonOne** [comment]
@tianzhi0549 I ran it in the root directory
Finally, after reinstalling torch and torchvision in a clear env(without apex), the code start running.
Thanks for your patient reply and your excellent work!

**Comment by tianzhi0549** [comment]
@SkeletonOne Happy to know that.
