### ISSUE TITLE
How many time i need to train a converged model? 

### ISSUE THREAD

**Issue by houweidong** [tianzhi0549/FCOS#11]
I have 8 1080ti Gpu, How many time i need to train a converged model?

**Comment by tianzhi0549** [comment]
@houweidong The best number of iterations depends on how many training images you have. For our released models, we use 90K iterations or 180K iterations as indicated by 1x or 2x in their names.

**Comment by houweidong** [comment]
@tianzhi0549  Thanks for your reply, i just want to train the coco dataset, and i have 8 1080ti(not V100), so i don't know how time i will consume.

**Comment by tianzhi0549** [comment]
@houweidong It should need about 10 hours on 8x 1080Ti GPUs.

**Comment by houweidong** [comment]
@tianzhi0549  thank for your reply again
你是Chinese吗？ 是的话，可不可以加个qq或者微信呀?
 if you are not, can i hold a seat in your facebook?

**Comment by tianzhi0549** [comment]
You can email me if you have some problems you don't want to post here. My email is on my GitHub homepage.

**Comment by houweidong** [comment]
OK, thanks
