### ISSUE TITLE
Only one box per location?

### ISSUE THREAD

**Issue by lsrock1** [tianzhi0549/FCOS#111]
Hello!
Thank you for your wonderful paper and code!
I have a question about your code in inference.
In your implementation, using sigmoid to box_cls. so, more than one classes can be extracted in same feature map location.
https://github.com/tianzhi0549/FCOS/blob/dde675435d05a1a63149b2ad8ceabbdf76221a3e/fcos_core/modeling/rpn/fcos/inference.py#L66

If chair and person classes are extracted in same location and even same feature map level, they would have same box regression. Am i right?
https://github.com/tianzhi0549/FCOS/blob/dde675435d05a1a63149b2ad8ceabbdf76221a3e/fcos_core/modeling/rpn/fcos/inference.py#L79-L81

**Comment by tianzhi0549** [comment]
Yes, you are right.
