### ISSUE TITLE
grouped_batch_sampler issue : IndexError: index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by heng2j** [tianzhi0549/FCOS#112]
Hi @tianzhi0549 ,

I was able to train with the previous version. However, after last night's updates, there are couple things seems breaking on grouped_batch_sampler. I even tried to build and rebuild already. But still not working.

Following are the error I see during training:

> Done (t=0.01s)
> creating index...
> index created!
> loading annotations into memory...
> Traceback (most recent call last):
>   File "tools/train_net.py", line 180, in <module>
>     main()
>   File "tools/train_net.py", line 173, in main
>     model = train(cfg, args.local_rank, args.distributed)
>   File "tools/train_net.py", line 79, in train
>     arguments,
>   File "../FCOS/fcos_core/engine/trainer.py", line 57, in do_train
>     for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
>   File ".../env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File ".../env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
>     self._try_put_index()
>   File "../env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
>     index = self._next_index()
>   File ".../env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
>     return next(self.sampler_iter)  # may raise StopIteration
>   File "../FCOS/fcos_core/data/samplers/iteration_based_batch_sampler.py", line 24, in __iter__
>     for batch in self.batch_sampler:
>   File "../FCOS/fcos_core/data/samplers/grouped_batch_sampler.py", line 107, in __iter__
>     batches = self._prepare_batches()
>   File "../FCOS/fcos_core/data/samplers/grouped_batch_sampler.py", line 79, in _prepare_batches
>     first_element_of_batch = [t[0].item() for t in merged]
>   File "../FCOS/fcos_core/data/samplers/grouped_batch_sampler.py", line 79, in <listcomp>
>     first_element_of_batch = [t[0].item() for t in merged]
> IndexError: index 0 is out of bounds for dimension 0 with size 0
> 
> Done (t=0.06s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> Traceback (most recent call last):
> ...
>  subprocess.CalledProcessError: Command '['/env/bin/python', '-u', 'tools/train_net.py', '--local_rank=3', '--config-file', 'configs/fcos/fcos_R_101_FPN_2x.yaml', 'DATALOADER.NUM_WORKERS', '2', 'OUTPUT_DIR', 'training_dir/fcos_R_101_FPN_2x']' returned non-zero exit status 1.

I am training with my own dataset with the pertained weight: **FCOS_R_101_FPN_2x.pth**
My dataset only has 1 class 

Can you advise? Greatly appreciated

**Comment by tianzhi0549** [comment]
Can you train with the original coco dataset?

**Comment by heng2j** [comment]
Hi @tianzhi0549, I haven't try to train with the original coco dataset. And I probably won't train with  the original coco dataset. My dataset is already in proper coco-style and I have verified that with the cocoapi. I was able to train the model with your previous code. Really need to dig in to see what is breaking at this point. Can you advice?

**Comment by tianzhi0549** [comment]
@heng2j Can you try to run `pip install torchvision==0.2.1 --ignore-installed`?

**Comment by heng2j** [comment]
Hi @tianzhi0549, I finally came back to this last week. And realized that the issue due to the distribution of images with different aspect ratios. I fixed this by turning off aspect ratio grouping.

    _C.DATALOADER.ASPECT_RATIO_GROUPING = False

Over the weekend I just trained a model, VoVNet-FCOS model with my dataset that gave us the highest AP. Thank you and @stigma0617  for the hard works! 


FYI, while I was fixing this, I also discovered another possible issue for dataset that doesn't has masks.  The current focs_core/data/datasets/coco.py seems missing the updates from this [PR](https://github.com/facebookresearch/maskrcnn-benchmark/pull/814) from maskrcnn-benchmark.

I just made a minor fix. Please let me know if you need a PR from your end.

**Comment by tianzhi0549** [comment]
@heng2j Good to know this. But my question is that why the code before the updates works well?

**Comment by heng2j** [comment]
Hi @tianzhi0549, it was also due to I further filtered out my dataset. So the dataset size is about half of what it was before.

**Comment by tianzhi0549** [comment]
@heng2j OK. Thank you for letting me know this.
