### ISSUE TITLE
How does the best possible recalls calculated?

### ISSUE THREAD

**Issue by Epiphqny** [tianzhi0549/FCOS#113]
In section 4.1.1 of the paper, it says the iou threshold of RetinaNet is 0.4, i want to ask the iou threshold of FCOS is what? what's the meaning of a successful recall for FCOS?

**Comment by tianzhi0549** [comment]
@Epiphqny No threshold is involved in the FCOS in our paper.

**Comment by Epiphqny** [comment]
> @Epiphqny No threshold is involved in the FCOS in our paper.

Then what's the meaning of a successful recall for FCOS?

**Comment by Epiphqny** [comment]
a

**Comment by tianzhi0549** [comment]
@Epiphqny If at least one location on the feature maps is assigned to the ground-truth box, the ground-truth box is considered recalled.

**Comment by Epiphqny** [comment]
> @Epiphqny If at least one location on the feature maps is assigned to the ground-truth box, the ground-truth box is considered recalled.

Ok, excellent work, thanks for your reply!
