### ISSUE TITLE
FCOS is too sensitive to batch size?

### ISSUE THREAD

**Issue by karlind** [tianzhi0549/FCOS#115]
Hi, I use FCOS implemented in [mmdetection](https://github.com/open-mmlab/mmdetection) to my own dataset, but I find FCOS is too sensitive to batch size.
Performance for different batch size may differ to almost 10%.
I tried to adjust learning rate to fit batch size(linear to batch size), but it don't help. 
@hellock suggest me to ask the authors(https://github.com/open-mmlab/mmdetection/issues/1178)
Have you ever suffered such problem? Or is there any clue for this?

**Comment by tianzhi0549** [comment]
@karlind I only run experiments on COCO and I have not met this problem. Is FCOS the only one that sensitive to batch size? Have you tried other detectors such as Faster R-CNN or RetinaNet? I just want to make sure it is not the problem of your dataset.

**Comment by karlind** [comment]
I have tried `Faster RCNN` and `Cascade RCNN`, they works fine. Only FCOS has met this problem.

**Comment by tianzhi0549** [comment]
@karlind Have you tried other one-stage detectors such as RetinaNet?
