### ISSUE TITLE
Trying to train FCOS with different batch size

### ISSUE THREAD

**Issue by liyz15** [tianzhi0549/FCOS#119]
I'm trying to train FCOS_R_50_FPN_1x with batch size of 4. I changed BASE_LR to 0.0025 and after 360k iters, mAP on coco2017_val is only 35.9.

Is there anything I missed such as WARMUP_ITERS or WEIGHT_DECAY? Or is it FCOS just can not able to be trained with different batch size?

**Comment by tianzhi0549** [comment]
@liyz15 To me, it's normal. There is no guarantee that the linear scaling policy can result in the same performance.

**Comment by liyz15** [comment]
Thanks for your reply!
