### ISSUE TITLE
wrong memory number in README

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [tianzhi0549/FCOS#12]
hi @tianzhi0549 
is there something wrong for the memory in [README](https://github.com/tianzhi0549/FCOS/blob/master/README.md#L45)?

**Comment by tianzhi0549** [comment]
@zimenglan-sysu-512 They should be correct. Just to be clear, our training memory footprint is computed by `torch.cuda.max_memory_allocated()`. We report the total training memory on all GPUs.
