### ISSUE TITLE
How to get l, r, t, b parameters?

### ISSUE THREAD

**Issue by ElPatou** [tianzhi0549/FCOS#122]
Hi, I am interested in finding something like the center of gravity of the objects. How do you get those four parameters (fig 1 of the paper) from the network? All I see is the bounding box.

Thanks

**Comment by tianzhi0549** [comment]
@ElPatou they are stored in `per_box_regression` at https://github.com/tianzhi0549/FCOS/blob/efb76e48e6490a93cc8b6b5dc93738fa1df34af5/fcos_core/modeling/rpn/fcos/inference.py#L96.

**Comment by ElPatou** [comment]
Thanks
