### ISSUE TITLE
How can I converting the  model to torch script, I failed to do that with 'torch.jit.trace'

### ISSUE THREAD

**Issue by xscjun** [tianzhi0549/FCOS#123]
I would like to load the model in C++ . Than how can I converting the  model to torch script ? I failed to do that with 'torch.jit.trace( self.model,example)', because of the Boxlist type error.

**Comment by tianzhi0549** [comment]
@xscjun this issue (https://github.com/tianzhi0549/FCOS/issues/57) might be helpful.

**Comment by xscjun** [comment]
> @xscjun this issue (#57) might be helpful.
Thanks, I will try in this way

**Comment by xscjun** [comment]
> @xscjun this issue (#57) might be helpful.

I have done this work , and apply this model with libtorch with c++.  
Now the problem is the time efficiency, in pytorch the codes like " per_box_cls = per_box_cls(per_candidate_inds] )", I cound not convert the code into  libtorch without "for(;;)",  so the testing time is 10*(pytorch speed). How can I deal with it , please ?

**Comment by xscjun** [comment]
> @xscjun this issue (#57) might be helpful.

**Comment by xscjun** [comment]
I have done it.

**Comment by sathyamsn** [comment]
@xscjun , I'm also trying to convert the model to torchscript. Could you please share the code. Thanks!
