### ISSUE TITLE
pos_inds

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#125]
My dataset only has 1 class, and labels from targets are zeros, so if i run the code bellow:
pos_inds = torch.nonzero(labels_flatten > 0).squeeze(1)

the result is empty, hence, centerness_loss and reg_loss are empty too.

What should I do to fix it?

**Comment by Baby47** [comment]
Hi @ mama110, I have encountered the same problem , the pos_inds is all zero. 
Have you figured out this question and give me some suggestions?
Thank you

**Comment by mama110** [comment]
Because my dataset only has one label, and the label index is 0, so all the pos_inds is 0. I've modify the label index to 1, and I solved it.
