### ISSUE TITLE
prepare targets for multiple object

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#126]
In function: compute_targets_for_locations, code as follows:
        for im_i in range(len(targets)):
            targets_per_im = targets[im_i]

Is this code for one single object in one image only?
If there are several objects in one  image, what should I do to support that ?

**Comment by tianzhi0549** [comment]
@mama110 No, the code supports multiple objects in an image.

**Comment by mama110** [comment]
@tianzhi0549 got it, thanks.
