### ISSUE TITLE
I train the net on coco2017, but get a problem on transformer Resize

### ISSUE THREAD

**Issue by cunjif** [tianzhi0549/FCOS#127]
I try to train the network on coco2017 by two gpus 1080ti. During in loading the dataset, I get an error.
![fcos](https://user-images.githubusercontent.com/11575215/64178792-aa59bc00-ce94-11e9-9b99-846e5930398b.png)
Then I insert a print statement ino there to output image and target.
https://github.com/tianzhi0549/FCOS/blob/efb76e48e6490a93cc8b6b5dc93738fa1df34af5/fcos_core/data/transforms/transforms.py#L58
And somthing I get as follow.
![2019-09-03 21-52-25屏幕截图](https://user-images.githubusercontent.com/11575215/64179139-38ce3d80-ce95-11e9-9e5e-815c690fde98.png)
And now, I dont know what happen and how to fix it. 
Please!

**Comment by tianzhi0549** [comment]
@cunjif please try `pip install torchvision==0.2.1`.

**Comment by cunjif** [comment]
@tianzhi0549 it can run! Thanks ! Y(^v^)Y
