### ISSUE TITLE
about bceloss

### ISSUE THREAD

**Issue by GGjerry01** [tianzhi0549/FCOS#13]
why use becloss to do centerness prediction?

**Comment by tianzhi0549** [comment]
@GGjerry01 Because the center-ness is in the range [0, 1]. We also tried L2 and it yielded the same performance. But you can still try to use other loss functions, maybe you will find a better one.

**Comment by GGjerry01** [comment]
thanks reply. if centerness target is 0.5, then net predict centerness is 0.5. so the loss should be 0,but if i use bceloss, the loss is not 0, so i am very confusing about this loss. otherwise if i misunderstanding the centerness function




------------------ 原始邮件 ------------------
发件人: "Tian Zhi"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 下午3:26
收件人: "tianzhi0549/FCOS"<FCOS@noreply.github.com>; 
抄送: "皮皮桂"<534501712@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tianzhi0549/FCOS] about bceloss (#13)




@GGjerry01 Because the center-ness is in the range [0, 1]. We also tried L2 and it yielded the same performance. But you can still try to use other loss functions, maybe you will find a better one.

**Comment by tianzhi0549** [comment]
@GGjerry01 The loss value is not important, we only care about if it is the minima. If you want its minima being 0, please try KL divergence instead.

**Comment by GGjerry01** [comment]
ok thanks very much




------------------ 原始邮件 ------------------
发件人: "Tian Zhi"<notifications@github.com>; 
发送时间: 2019年4月23日(星期二) 下午3:43
收件人: "tianzhi0549/FCOS"<FCOS@noreply.github.com>; 
抄送: "皮皮桂"<534501712@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tianzhi0549/FCOS] about bceloss (#13)




@GGjerry01 The loss value is not important, we only care about if it is the minima. If you want its minima being 0, please try KL divergence instead.

**Comment by soldier828** [comment]
> why use becloss to do centerness prediction?

The same question.
After some search, I found a keyword 'bce soft target'. 
In official definition of bceloss, the target is a float between 0 and 1(namely [0,1]).  
So maybe the author actually want to use soft label, and bceloss just can achieve it.

**Comment by tianzhi0549** [comment]
@soldier828 Yes, it can be understood as the BCE with soft targets.
