### ISSUE TITLE
train stopped

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#130]
When I trained coco2014 dataset, it stopped immediately.

loading annotations into memory...
Done (t=7.49s)
creating index...
index created!
loading annotations into memory...
Done (t=5.17s)
creating index...
index created!
2019-09-04 11:38:50,505 maskrcnn_benchmark.trainer INFO: Start training
2019-09-04 11:38:50,751 maskrcnn_benchmark.trainer INFO: Total training time: 0:00:00.245872 (0.0000 s / it)

Why is that?

**Comment by dreamhighchina** [comment]
@mama110 i meet the same error as you，could you please tell me how you solve it？？？

**Comment by tianzhi0549** [comment]
@mama110 This issue might be helpful. https://github.com/tianzhi0549/FCOS/issues/30#issuecomment-489888580
