### ISSUE TITLE
How to train in images without targets

### ISSUE THREAD

**Issue by adizhol** [tianzhi0549/FCOS#131]
Hi,

I need to add negative samples to my training, but FCOS doesn't support targets with BoxList of 0 bboxes.
How would you suggest to change the code to support this?

Thanks

**Comment by tianzhi0549** [comment]
@adizhol I think you can add some code here to implement it. https://github.com/tianzhi0549/FCOS/blob/efb76e48e6490a93cc8b6b5dc93738fa1df34af5/fcos_core/modeling/rpn/fcos/loss.py#L82

If `targets` has no elements, just fill `labels_per_im` and `reg_targets_per_im` with all zeros and append them to `labels` and `reg_targets`, repectively.

**Comment by adizhol** [comment]
@tianzhi0549 
Thanks, I actually tried to do just that. I wasn't sure it was the correct way.
