### ISSUE TITLE
pos_inds number bug in loss function in fcos

### ISSUE THREAD

**Issue by Baby47** [tianzhi0549/FCOS#139]
When I apply this project on my own dataset (one category), I have encountered this problem in modeling/rpn/fcos/loss.py, the corresponding code is: line [267](https://github.com/tianzhi0549/FCOS/blob/master/fcos_core/modeling/rpn/fcos/loss.py)  

There is no positive samples in my dataset (pos_inds.numel() is not bigger than zero). so the loss of regression and centerness is always 0.

Could you give me some suggestions? Thanks

**Comment by tianzhi0549** [comment]
@Baby47 How about the object sizes in your dataset?
