### ISSUE TITLE
Data preparation error

### ISSUE THREAD

**Issue by Hwang64** [tianzhi0549/FCOS#14]
When i train the network using my own data, there is a mistake:

TypeError: Traceback (most recent call last):
  File "/home/wh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/wh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/wh/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 234, in default_collate
    raise TypeError((error_msg.format(type(batch[0]))))
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'maskrcnn_benchmark.structures.bounding_box.BoxList'>

I follow the same configurations and data preparation process and I find Line 71 in maskrcnn_benchmark/data/dataset/voc.py, the return parameter is target which is a BoxList, so is there any modification I miss? Thanks a lot!

**Comment by tianzhi0549** [comment]
@Hwang64 Did you follow `Adding your own dataset` in https://github.com/tianzhi0549/FCOS/blob/master/MASKRCNN_README.md?

**Comment by Hwang64** [comment]
@tianzhi0549 I have follow the readme to handle the data, however, a error happen when starting training, I wonder if there any operation to change the BoxList to other data types, like lists.

**Comment by tianzhi0549** [comment]
@Hwang64 We can't get too much information from the stack you posted. We suggest that you follow the coco dataset instead of voc dataset because we are sure coco dataset works well.

**Comment by roeiherz** [comment]
Also, happens to me when try to return list of BoxList in dataloader. Do you know what is the reason for that? @Hwang64 ?
