### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by dreamhighchina** [tianzhi0549/FCOS#142]
File "/home/112831/Anaconda/lib/python3.6/site-packages/fcos_core/layers/nms.py", line 3, in <module>
    from fcos_core import _C
ImportError: /home/112831/Anaconda/lib/python3.6/site-packages/fcos_core/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
my python is anaconda（python 3.6.5），cuda is 8.0 driver is 390.77

**Comment by tianzhi0549** [comment]
@dreamhighchina Please create a new virtual environment and try to recompile the project.
