### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dreamhighchina** [tianzhi0549/FCOS#143]
/usr/local/cuda/bin/nvcc -DWITH_CUDA -Ifcos_core/csrc -I/home/112831/Anaconda3/lib/python3.7/site-packages/torch/lib/include -I/home/112831/Anaconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/112831/Anaconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/112831/Anaconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/112831/Anaconda3/include/python3.7m -c fcos_core/csrc/cuda/ROIPool_cuda.cu -o build/temp.linux-x86_64-3.7/fcos_core/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    /home/112831/Anaconda3/lib/python3.7/site-packages/torch/lib/include/c10/Half-inl.h(21): error: identifier "__half_as_short" is undefined
    
    1 error detected in the compilation of "/tmp/tmpxft_00015ee8_00000000-7_ROIPool_cuda.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
    ----------------------------------------
ERROR: Command "/home/112831/Anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-gof_iivp/fcos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0xwpvquv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-gof_iivp/fcos/
 
my gcc version is gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)，anaconda3（python3.7），cuda is 8.0，please help me。。。。

**Comment by tianzhi0549** [comment]
@dreamhighchina Please use gcc>=5.0,<6.0.
