### ISSUE TITLE
train loss is always unchanged

### ISSUE THREAD

**Issue by dreamhighchina** [tianzhi0549/FCOS#149]
19-09-21 00:51:36,413 fcos_core.trainer INFO: eta: 1 day, 0:04:04  iter: 69740  loss: 0.8339 (0.9184)  loss_centerness: 0.5668 (0.5709)  loss_cls: 0.0916 (0.1203)  loss_reg: 0.1802 (0.2272)  time: 0.7790 (0.7858)  data: 0.0104 (0.0146)  lr: 0.010000  max mem: 8322

from the begining to the  iter: 69740，the total loss doesnot change （keep 0.7956 -0.9161）。

**Comment by tianzhi0549** [comment]
@dreamhighchina Please make sure your code for computing training targets is correct.
