### ISSUE TITLE
question about offset gt generation

### ISSUE THREAD

**Issue by kfxw** [tianzhi0549/FCOS#154]
Hi! As shown in the following code (line 176-180)
https://github.com/tianzhi0549/FCOS/blob/18191872ec9dff2eebd1560fe9e702a9f9d67714/fcos_core/modeling/rpn/fcos/loss.py#L176
I would like to know whether this operation will cause an entire box area splitted into different stages? And whether is that reasonable?

**Comment by kfxw** [comment]
To my understanding, such an operation means 'assign each pixel to a stage according to its **max offset'** rather than based on the longest bbox side as claimed in the paper.

**Comment by tianzhi0549** [comment]
@kfxw yes. The same object might be assigned to different FPN levels. However, that is by design and aligned with the statement in our paper. Note that we hope that for each pixel, the whole object is included in its receptive field, so we choose to use the max offset.

**Comment by kfxw** [comment]
@tianzhi0549 
Got it! Thx!
