### ISSUE TITLE
only test error

### ISSUE THREAD

**Issue by dreamhighchina** [tianzhi0549/FCOS#155]
when i test FCOS_R_50_FPN_1x.pth,the error is：
root@gpu58-1080ti-cuda_112831:/home/112831/code/FCOS-master# python demo/fcos_demo.py 
COCO_val2014_000000000885.jpg	inference time: 0.69s
: cannot connect to X server 

The FCOS_R_50_FPN_1x.pth is downloaded on your github，and i dont change any code。what should i do ？？？？looking forward to your reply。

**Comment by tianzhi0549** [comment]
@dreamhighchina it is because you do not forward X server to your local computer. Please connect to your server with `ssh -X username@ip`.

**Comment by dreamhighchina** [comment]
thanks！！！

**Comment by qingchengboy** [comment]
@dreamhighchina 您好，你是在docker环境下运行的吧。我也遇见这个问题了，但是按照2楼的解决方案，是连接到宿主机器上了。问一下最后是怎么解决的？

**Comment by dreamhighchina** [comment]
@qingchengboy 没有按照他的方法解决，因为缺少QT的显示界面，你去掉imshow()这个函数就好了，改为imwrite()保存下来。
