### ISSUE TITLE
test with FCOS_imprv_R_101_FPN_2x very low map?

### ISSUE THREAD

**Issue by zlheos** [tianzhi0549/FCOS#158]
I test coco with FCOS_imprv_R_101_FPN_2x
but the result is very low map

I don't know why?

**Comment by tianzhi0549** [comment]
@zlheos Please post your results here.

**Comment by zlheos** [comment]
I download false model with 
wget https://cloudstor.aarnet.edu.au/plus/s/ZSAqNJB96hA71Yf/download -O FCOS_imprv_R_101_FPN_2x.pth
