### ISSUE TITLE
What's the inference speed?

### ISSUE THREAD

**Issue by auroua** [tianzhi0549/FCOS#16]
What's the inference speed of `FCOS` with `ResNet-101-FPN` and `ResNeXt-32x8d-101-FPN` backbone. The input image size is consistency with the training setting.

**Comment by tianzhi0549** [comment]
@auroua The inference speed can be found in the table in our README.md.

**Comment by auroua** [comment]
Thanks!

**Comment by dongfangduoshou123** [comment]
Hi tianzhi0549,
   I want to know since it is one stage and anchor-free,  why its inference time is a bit long then than the one-stage and anchor-based yolov3 detector?   if fcos's speed can reach to more than 25fps, that is very fine!

**Comment by tianzhi0549** [comment]
@dongfangduoshou123 I think it is mainly because we use larger input size (i.e., 800). If you want faster speed, please use smaller input size. for example 600.

**Comment by dongfangduoshou123** [comment]
@tianzhi0549 Thank you for your reply, have you test input size 600 or 416, how mush decrease in AP contrast to 800?

**Comment by tianzhi0549** [comment]
@dongfangduoshou123 We have not tested them. It needs to re-train the models with the sizes.

**Comment by glenn-jocher** [comment]
@tianzhi0549 I have a question about the inference speeds presented in https://github.com/tianzhi0549/FCOS#models

- What hardware are these run on (and single or multiple GPU)?
- What is the batch-size?
- What is the img-size?
- Do these include NMS times?

Thank you!
