### ISSUE TITLE
ImportError: /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by codylcs** [tianzhi0549/FCOS#160]
when i run fcos_demo.py, questions happpend as flow:

ImportError: /home/cody/PycharmProjects/FCOS/FCOS-master/fcos_core/_C.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

my install versions  list:
certifi                   2016.2.28                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cycler                    0.10.0                    <pip>
Cython                    0.29.13                   <pip>
decorator                 4.4.0                     <pip>
decorator                 4.1.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
imageio                   2.5.0                     <pip>
ipython                   6.1.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ipython_genutils          0.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jedi                      0.10.2                   py36_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
kiwisolver                1.1.0                     <pip>
matplotlib                3.1.1                     <pip>
networkx                  2.3                       <pip>
ninja                     1.9.0.post1               <pip>
numpy                     1.17.2                    <pip>
opencv-python             4.1.0.25                  <pip>
openssl                   1.0.2l                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
path.py                   10.3.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pexpect                   4.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pickleshare               0.7.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Pillow                    6.2.0                     <pip>
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
prompt_toolkit            1.0.15                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ptyprocess                0.5.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pygments                  2.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 2.4.2                     <pip>
python                    3.6.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.8.0                     <pip>
PyWavelets                1.0.3                     <pip>
PyYAML                    5.1.2                     <pip>
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scikit-image              0.15.0                    <pip>
scipy                     1.3.1                     <pip>
setuptools                36.4.0                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
simplegeneric             0.8.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
torch                     1.1.0                     <pip>
torchvision               0.2.0                     <pip>
tqdm                      4.36.1                    <pip>
traitlets                 4.3.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wcwidth                   0.1.7                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
yacs                      0.1.6                     <pip>
zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by codylcs** [comment]
thanks for anyone who can tackle this question

**Comment by codylcs** [comment]
when after run command:  
python setup.py build_ext install
the information like this,any questions?


running build_ext
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
running install
running bdist_egg
running egg_info
writing pycocotools.egg-info/PKG-INFO
writing dependency_links to pycocotools.egg-info/dependency_links.txt
writing requirements to pycocotools.egg-info/requires.txt
writing top-level names to pycocotools.egg-info/top_level.txt
reading manifest file 'pycocotools.egg-info/SOURCES.txt'
writing manifest file 'pycocotools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-3.6/pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-3.6/pycocotools/__init__.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-3.6/pycocotools/cocoeval.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-3.6/pycocotools/mask.py -> build/bdist.linux-x86_64/egg/pycocotools
copying build/lib.linux-x86_64-3.6/pycocotools/coco.py -> build/bdist.linux-x86_64/egg/pycocotools
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/cocoeval.py to cocoeval.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/mask.py to mask.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/coco.py to coco.cpython-36.pyc
creating stub loader for pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/pycocotools/_mask.py to _mask.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pycocotools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pycocotools.__pycache__._mask.cpython-36: module references __file__
creating 'dist/pycocotools-2.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pycocotools-2.0-py3.6-linux-x86_64.egg
removing '/home/cody/anaconda3/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg' (and everything under it)
creating /home/cody/anaconda3/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg
Extracting pycocotools-2.0-py3.6-linux-x86_64.egg to /home/cody/anaconda3/lib/python3.6/site-packages
pycocotools 2.0 is already the active version in easy-install.pth

Installed /home/cody/anaconda3/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg
Processing dependencies for pycocotools==2.0
Searching for matplotlib==2.2.2
Best match: matplotlib 2.2.2
Adding matplotlib 2.2.2 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for Cython==0.28.2
Best match: Cython 0.28.2
Adding Cython 0.28.2 to easy-install.pth file
Installing cygdb script to /home/cody/anaconda3/bin
Installing cython script to /home/cody/anaconda3/bin
Installing cythonize script to /home/cody/anaconda3/bin

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for setuptools==36.4.0
Best match: setuptools 36.4.0
Adding setuptools 36.4.0 to easy-install.pth file
Installing easy_install script to /home/cody/anaconda3/bin
Installing easy_install-3.6 script to /home/cody/anaconda3/bin

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for kiwisolver==1.0.1
Best match: kiwisolver 1.0.1
Adding kiwisolver 1.0.1 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for pytz==2018.4
Best match: pytz 2018.4
Adding pytz 2018.4 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for python-dateutil==2.7.3
Best match: python-dateutil 2.7.3
Adding python-dateutil 2.7.3 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Searching for numpy==1.14.3
Best match: numpy 1.14.3
Adding numpy 1.14.3 to easy-install.pth file

Using /home/cody/anaconda3/lib/python3.6/site-packages
Finished processing dependencies for pycocotools==2.0

**Comment by codylcs** [comment]
maybe question is that:
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 

i use ubuntu 18.04,gcc++ is 7.4.0 ,which is higer than 6.0

**Comment by codylcs** [comment]
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1) 

however,it doesnot work

**Comment by tianzhi0549** [comment]
@codylcs please clone the project again and re-compile it.

**Comment by codylcs** [comment]
thanks,change torch version to torchvision==0.2.1,it works
@tianzhi0549

**Comment by 77philosophia** [comment]
The reason is that you use different version of pytorch when you compile and run.  rm -rf build and compile again. I use this method and solve my problem.
https://github.com/facebookresearch/maskrcnn-benchmark/issues/421
