### ISSUE TITLE
A question related to FPN

### ISSUE THREAD

**Issue by Remember2018** [tianzhi0549/FCOS#169]
Hi there, thanks a lot for sharing your code!

I have a question about the following description in the paper:
![F98301C6-4925-4723-94AA-0650E29230F8](https://user-images.githubusercontent.com/43327429/66623283-86b92c80-ec1d-11e9-8f2a-002346564b0b.png)
Why is the `s/2` adopted in the formula? Could you please give some advice? Thanks a lot!

**Comment by tianzhi0549** [comment]
@Remember2018 It is a convention since Region Proposal Networks (RPN) in Faster R-CNN.

**Comment by Remember2018** [comment]
@tianzhi0549 Thanks a lot for your kind reply! Yeah, I got it. It seems in the Faster-RCNN, the computation of coordinates of anchors is based on `s`, not `s/2`. So in your paper, the regression of bounding boxes is based on the RPN.
