### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by Zeqiang** [tianzhi0549/FCOS#173]
@tianzhi0549 求助
# Sena
Trying to run inference on coco 14 minival set, but even single img demo has CUDA error for invalid device function

# Env:
CUDA 10.2
pytorch 1.3
Single GPU

# Run:
python tools/test_net.py 
--config-file fcos_R_50_FPN_1x.yaml  
MODEL.WEIGHT FCOS_R_50_FPN_1x.pth 
TEST.IMS_PER_BATCH 1

# Error Message:
Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 91, in main
    output_folder=output_folder,
  File "/home/zeqiang/gitlab/FCOS/fcos_core/engine/inference.py", line 83, in inference
    predictions = compute_on_dataset(model, data_loader, device, inference_timer)
  File "/home/zeqiang/gitlab/FCOS/fcos_core/engine/inference.py", line 30, in compute_on_dataset
    output = model(images.to(device))
  File "/home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zeqiang/gitlab/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zeqiang/gitlab/FCOS/fcos_core/modeling/rpn/fcos/fcos.py", line 164, in forward
    centerness, images.image_sizes
  File "/home/zeqiang/gitlab/FCOS/fcos_core/modeling/rpn/fcos/fcos.py", line 181, in _forward_test
    centerness, image_sizes
  File "/home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zeqiang/gitlab/FCOS/fcos_core/modeling/rpn/fcos/inference.py", line 137, in forward
    boxlists = self.select_over_all_levels(boxlists)
  File "/home/zeqiang/gitlab/FCOS/fcos_core/modeling/rpn/fcos/inference.py", line 150, in select_over_all_levels
    result = boxlist_ml_nms(boxlists[i], self.nms_thresh)
  File "/home/zeqiang/gitlab/FCOS/fcos_core/structures/boxlist_ops.py", line 55, in boxlist_ml_nms
    keep = _box_ml_nms(boxes, scores, labels.float(), nms_thresh)
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/ATen/native/cuda/Loops.cuh:102)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7efcfd334687 in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x78d (0x7efd0441c07d in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x543e822 (0x7efd04415822 in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x543ecd8 (0x7efd04415cd8 in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x16a5efb (0x7efd0067cefb in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x44e (0x7efd00677d2e in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x1b9d04a (0x7efd00b7404a in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x366f7ad (0x7efd026467ad in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0xbb (0x7efd0230d53b in /home/zeqiang/miniconda3/envs/fcos/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: ml_nms_cuda(at::Tensor, float) + 0x79a (0x7efcd96338f0 in /home/zeqiang/gitlab/FCOS/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so)
frame #10: ml_nms(at::Tensor const&, at::Tensor const&, at::Tensor const&, float) + 0xe6 (0x7efcd95ecf36 in /home/zeqiang/gitlab/FCOS/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x4da04 (0x7efcd95fea04 in /home/zeqiang/gitlab/FCOS/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x4aa1a (0x7efcd95fba1a in /home/zeqiang/gitlab/FCOS/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>

Segmentation fault (core dumped)

**Comment by zm379096736** [comment]
How do you solve it?

**Comment by Zeqiang** [comment]
@zm379096736 wrong version of cudatoolkit during installation for pytorch

**Comment by zm379096736** [comment]
> @zm379096736 wrong version of cudatoolkit during installation for pytorch

thanks, that's it.
