### ISSUE TITLE
About Multi-Label NMS

### ISSUE THREAD

**Issue by stigma0617** [tianzhi0549/FCOS#175]
Hi, it is awesome that the speed of FCOS is boosted by [Multi-Label NMS](https://github.com/tianzhi0549/FCOS/pull/165#issue-325758674). 

I want to the details of Multi-Label NMS. Could you explain more details? or Is there any reference?

**Comment by tianzhi0549** [comment]
@stigma0617 The previous implementation uses for loop in python to do multi-class NMS. In this PR, NMS for all classes is done together. If two bounding-boxes are with different classes, their overlap is set as 0.

**Comment by stigma0617** [comment]
@tianzhi0549 Thanks for your reply :)

**Comment by glenn-jocher** [comment]
@tianzhi0549 does multi-label NMS provide a mAP increase compared to single-label NMS, and if so how much? Thank you.

**Comment by Auth0rM0rgan** [comment]
Hey @tianzhi0549, I couldn't find the implementation of python Multi-Label NMS in your repo. Would you please where is your python Multi-Label NMS implementation?

Thanks,

**Comment by glenn-jocher** [comment]
@Auth0rM0rgan we've implemented this here:
https://github.com/ultralytics/yolov3

It lead to a mAP increase during inference on COCO. See https://github.com/ultralytics/yolov3/issues/679

**Comment by Auth0rM0rgan** [comment]
@glenn-jocher thanks! Have you compare the performance of multi-label NMS with fast NMS, which introduced in yolact paper (I’m just curious)? thanks!

**Comment by glenn-jocher** [comment]
@Auth0rM0rgan I've not used fast NMS before, but glancing at the arxiv summary of the yolact paper it seems that its a faster implementation with slightly lower mAP, though I don't know if it is primarily aimed at box nms or semantic segmentation nms, or both.
