### ISSUE TITLE
Question on the num_class inconsistent between fco head and fco postprocessor

### ISSUE THREAD

**Issue by LouieYang** [tianzhi0549/FCOS#18]
Hi, I am a little curious about why using the different num_class in [fco head](https://github.com/tianzhi0549/FCOS/blob/de2d65a5e1ad01f0db2e16fdd4be682fd18a553b/maskrcnn_benchmark/modeling/rpn/fcos/fcos.py#L20) and in [fco postprocessor](https://github.com/tianzhi0549/FCOS/blob/de2d65a5e1ad01f0db2e16fdd4be682fd18a553b/maskrcnn_benchmark/modeling/rpn/fcos/inference.py#L200).

It seems like in preparing targets labels in [fcos loss](https://github.com/tianzhi0549/FCOS/blob/de2d65a5e1ad01f0db2e16fdd4be682fd18a553b/maskrcnn_benchmark/modeling/rpn/fcos/loss.py#L112), the "not in boxes" ones (background ones?) are marked as label 0.

**Comment by tianzhi0549** [comment]
@LouieYang the num_classes in FCOS head controls the number of outputs of the final classification layer.  We follow RetinaNet to use 80 binary classifiers instead of an 81-way softmax. The background class is encoded by an 80D vector with all elements being zeros. Hope the answer is clear.

**Comment by LouieYang** [comment]
Thank you. It is clear and will be closed.
