### ISSUE TITLE
Can I directly train the model "FCOS_imprv_dcnv2_X_101_64x4d_FPN_2x" with giving config?

### ISSUE THREAD

**Issue by Zeqiang** [tianzhi0549/FCOS#183]
GPU: 1080 Ti * 8
Config: fcos_imprv_X_101_64x4d_FPN_2x.yaml
Can I directly train the model and get 46.6 mAP?

BTW, you mentioned in the page that:
"State-of-the-art performance: Our best model based on ResNeXt-64x4d-101 and deformable convolutions achieves 49.0% in AP on COCO test-dev (with multi-scale testing)."
How can I do the testing and get same mAP

And according to the paper, the best mAP is 44.7, what u have changed to pushed to 46.6?

**Comment by tianzhi0549** [comment]
@Zeqiang All results can be reproduced by directly running our provided code.
Please checkout our model zoo for your other questions. https://github.com/tianzhi0549/FCOS#models

**Comment by Zeqiang** [comment]
@tianzhi0549 Thanks
