### ISSUE TITLE
center-ness loss

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#189]
Is there any way that I can reduce the loss of center-ness? I've trained the model and the best loss of center-ness is approximate to 0.54. Thanks.

**Comment by milliema** [comment]
The ideal value for centerness loss is 0.5, not 0. So in your case, 0.54 is already good enough.

**Comment by mama110** [comment]
The ideal value of centerness is 1.  Why the centerness loss is 0.5?  Because of BCE Loss?

**Comment by milliema** [comment]
https://github.com/tianzhi0549/FCOS/issues/15#issuecomment-487438717

**Comment by mama110** [comment]
@milliema Thank you.
