### ISSUE TITLE
您好，请问为何在inference_single_cv中没有使用centerness 

### ISSUE THREAD

**Issue by leoozy** [tianzhi0549/FCOS#19]
您好，非常感谢您的开源代码。我在使用inference_single_cvimage.py时，发现代码没有使用centerness，在centerness_loss时直接是一个conv2d(256,1)，并没有使用compute centerness函数，同时我在compute centerness函数那里加了断点，程序并没有暂停，说明程序确实没有执行：
`    def compute_centerness_targets(self, reg_targets):
        left_right = reg_targets[:, [0, 2]]
        top_bottom = reg_targets[:, [1, 3]]
        centerness = (left_right.min(dim=-1)[0] / left_right.max(dim=-1)[0]) * \
                      (top_bottom.min(dim=-1)[0] / top_bottom.max(dim=-1)[0])
        return torch.sqrt(centerness)`
请问下是有什么参数来控制么？为何在测试这里没有执行centerness，非常感谢！

**Comment by tianzhi0549** [comment]
@leoozy `compute_centerness_targets` is only used in *training* to compute the training targets for center-ness branch. When testing, center-ness scores are predicted by the trained center-ness branch.

**Comment by twmht** [comment]
@tianzhi0549 

Why don't you divide the centerness value instead of `torch.sqrt`?
