### ISSUE TITLE
How to enable Multi-scale training？

### ISSUE THREAD

**Issue by sunpeng981712364** [tianzhi0549/FCOS#193]
I don't see the related field in the config file. But in models, I see the multi-scale training option. Do you have ideas about it. Thanks for the great work. @tianzhi0549

**Comment by sunpeng981712364** [comment]
I don't see the related field in the config file.  But in models, I see the multi-scale training option.  Do you have ideas about it. Thanks for the great work.@tianzhi0549

**Comment by weihancug** [comment]
@sunpeng981712364   Do you know how to enable the multiscale training option？ Thanks for your reply
