### ISSUE TITLE
something wrong when install

### ISSUE THREAD

**Issue by murdockhou** [tianzhi0549/FCOS#21]
1. how to download pytorch 1.0.0 nightly? I can only download pytorch 1.1.0 nightly version.
2. Is cuda 9.0 not ok for this repo? I used cuda 9.0 and when run `python setup.py build develop` give wrong infomation `/usr/local/cuda/bin/nvcc: no such file or directory`.

**Comment by tianzhi0549** [comment]
@murdockhou 1) just try pytorch 1.1.0 nightly. If you encounter any problems, please post them here. We will help you as much as we can. 2) CUDA 9.0 should be OK. The error seems that your CUDA_HOME is configured correctly. Please try to run `export CUDA_HOME=the_location_of_your_cuda_installation` and then run `python setup.py build develop` again.

**Comment by murdockhou** [comment]
@tianzhi0549 problem solved as you said. run `export CUDA_HOME=the_location_of_your_cuda_installation` solved problem 2. About problem 1, i installed `pytorch` using command `pip install pytorch==1.0.0` also worked. `cuda 9.0` is okay either. 
Thanks again.

**Comment by wanglaotou** [comment]
i came across the same problem, and i run export CUDA_HOME = /usr/local/cuda10.1 did solve my problems, thanks. 
btw, my env is ubuntu16.04, cuda10.1, gcc 6.5.0, pytorch 1.3.0.
