### ISSUE TITLE
bbox_reg.append(bbox_pred * self.fpn_strides[l])

### ISSUE THREAD

**Issue by jszgz** [tianzhi0549/FCOS#211]
这一句是什么意思呢，为什么bbox_reg只有测试的时候需要乘以stride，
不太明白是什么意思，
另外，看这里的self.norm_reg_targets应该是True的，
那作者就是没有用论文里说的下面else里面的exp（）函数吧，
还有就是论文里作者说回归的都是正数，
所以直接用exp，
可是看这个if 的分支里面是先relu了，然后也没用exp，
不太懂是什么逻辑呢
https://github.com/tianzhi0549/FCOS/blob/master/fcos_core/modeling/rpn/fcos/fcos.py#L112

**Comment by tianzhi0549** [comment]
@jszgz when training, we instead normalize the training targets here.
https://github.com/tianzhi0549/FCOS/blob/dd4ca761f439a48a8c3003d1be74e9f85c050534/fcos_core/modeling/rpn/fcos/loss.py#L142

**Comment by jszgz** [comment]
Thx
