### ISSUE TITLE
Some questions about small object detection

### ISSUE THREAD

**Issue by weihancug** [tianzhi0549/FCOS#213]
I want to detect some vehicle objects from aerial images. The width of this kind of objects is about 10 ~ 20 pixels. My problems are as follows:
1) Do I need to apply the C2 layer of FPN to FCOS for small object detections?
2) If using  C2 of FPN, do I only need to modify the FPN stride to [4, 8, 16, 32, 64,128] ?

Thanks for your kind assistance for solving my problems.

**Comment by tianzhi0549** [comment]
1. You can try to use C2.
2. Yes, you need to change it.

**Comment by weihancug** [comment]
Thanks for your quickly replay. I have tried to increase the operation of stride 4, but found that the model is difficult to converge. The loss of  the class and regression reduced to 0.2~0.3 and did not change.  I just increase the number of convolutional body to 8 ,  which has a certain degree of effect. But the convergence is still slow.

Do you have any suggestions to speed up convergence

**Comment by tianzhi0549** [comment]
@weihancug Please double check your code and make sure it is correct.

**Comment by weihancug** [comment]
Thanks for your help, I would check it.
