### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by gengyanlei** [tianzhi0549/FCOS#225]
# from fcos_core import _C  这一行报错
from ._utils import _C

**Comment by yja1** [comment]
错误同上。不报错程序直接退出了。执行到losses = _C.sigmoid_focalloss_forward就退出了

**Comment by billyceline** [comment]
Did you compile the c lib before you ran the python script?
python setup.py build develop --no-deps

**Comment by Yudachi-poi-poi** [comment]
编译一下就好啦

**Comment by Linamiao-1998** [comment]
raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
 编译出现问题了，请问这种问题该如何解决呀 @Yudachi-poi-poi @billyceline

**Comment by tianzhi0549** [comment]
@Linamiao-1998 Could you please post the full error information here?
