### ISSUE TITLE
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by wanglaotou** [tianzhi0549/FCOS#226]
Hi, i run the test_net.py and get this error:
![image](https://user-images.githubusercontent.com/12837585/71608558-0cb19780-2bbd-11ea-9a26-e9847ca12155.png)
could you please tell me how to fix it, thanks.

**Comment by tianzhi0549** [comment]
@wanglaotou Please try to upgrade your numpy to `1.11.0`.

**Comment by wanglaotou** [comment]
thanks, i changed the version of numpy==1.17.4 and the problems solved. 
btw, my torch, torchvision, numpy, opencv version is:1.3.1, 0.2.1, 1.17.4, 4.1.2.
