### ISSUE TITLE
When you train FCOS, do you use pre-trained model of ResNets on ImageNet?

### ISSUE THREAD

**Issue by shoutOutYangJie** [tianzhi0549/FCOS#227]
I notice that at your training code, you don't use pretrained resnetx or other backbone with model pre-trained on ImageNet?  For your paper result, have you leveraged it ?

**Comment by billyceline** [comment]
The answer is yes.
The author mentioned this on the page 6.
![image](https://user-images.githubusercontent.com/7619955/72501434-b8234300-3871-11ea-9a5a-173d4217c9b5.png)
