### ISSUE TITLE
some question about loss.py in fcos file

### ISSUE THREAD

**Issue by gittigxuy** [tianzhi0549/FCOS#23]
Thanks for your work,I am reading your code and I have some questions.
in the loss.py in FCOS file,'level' comes several times,such as 'points_per_level','labels_level_first','reg_targets_level_first',So,what is the 'level' mean?,furthermore,what is the 'labels_level_first' and 'reg_targets_level_first' mean?

**Comment by tianzhi0549** [comment]
Level means FPN levels.
