### ISSUE TITLE
RuntimeError: CPU version not implemented (ml_nms at fcos_core/csrc/ml_nms.h:26)

### ISSUE THREAD

**Issue by alanMachineLeraning** [tianzhi0549/FCOS#235]
RuntimeError: CPU version not implemented (ml_nms at fcos_core/csrc/ml_nms.h:26)

**Comment by alanMachineLeraning** [comment]
when  I run  command “fcos https://github.com/tianzhi0549/FCOS/raw/master/demo/images/COCO_val2014_000000000885.jpg”

**Comment by jinzhenmu** [comment]
have you solved this problem?

**Comment by jinzhenmu** [comment]
- I have sovled this problem 

-  In    FCOS/fcos_core/csrc

- find  ml_nms.h

-
  if (dets.type().is_cuda()) {
#ifdef WITH_CUDA
    // TODO raise error if not compiled with CUDA
    if (dets.numel() == 0)
      return at::empty({0}, dets.options().dtype(at::kLong).device(at::kCPU));
    auto b = at::cat({dets, scores.unsqueeze(1), labels.unsqueeze(1)}, 1);
    return ml_nms_cuda(b, threshold);
#else
    AT_ERROR("Not compiled with GPU support");
#endif
  }
 // AT_ERROR("CPU version not implemented");
  return nms_cpu(dets, scores,threshold );
}

**Comment by whzz101** [comment]
good idea,  sovled this problem~
