### ISSUE TITLE
ImportError: cannot import name '_C' from 'fcos_core'

### ISSUE THREAD

**Issue by alanMachineLeraning** [tianzhi0549/FCOS#236]
ImportError: cannot import name '_C' from 'fcos_core'

**Comment by alanMachineLeraning** [comment]
when  I run command “python demo/fcos_demo.py”

**Comment by xiaopojizu123** [comment]
How did you solve the problem? Thanks !

**Comment by jieruyao49** [comment]
How did you solve the problem?
