### ISSUE TITLE
when test image, the score of some  object is low.

### ISSUE THREAD

**Issue by wadesunyang** [tianzhi0549/FCOS#24]
I have a question, why the scores are so low? such as the bike is 0.248 in your picture in #5 .

it also occur in my trained model, i trained the coco2017 with the code, and the score is always low, so i couldn't set the threshold, in my test, the people's score maybe 0.2-0.4 sometimes, when i set the threshold to 0.2, some false positive occur。

could you tell me how to solve the problem?

**Comment by tianzhi0549** [comment]
@wadesunyang it is a good question. We suggest you find the best threshold by maximizing F-measure (i.e., 2 * precision * recall / (precision * recall). As you change the threshold, you will get a pair of precision and recall. Just choose the threshold with the best F-measure.

**Comment by tianzhi0549** [comment]
@wadesunyang we have implemented it in our quick demo. Please check https://github.com/tianzhi0549/FCOS/blob/master/demo/fcos_demo.py for details.

**Comment by vandesa003** [comment]
@tianzhi0549 I also met the same problem. I also find that when I train FCOS on my own dataset, the classification is not good. Though the bound box is accurate, the classification label is wrong. Did you met this kind of problems? and how do you suggest to fix this?
