### ISSUE TITLE
Does FCOS handle two crossing objects with same center, same size, but only different orientation?

### ISSUE THREAD

**Issue by wuyuanyi135** [tianzhi0549/FCOS#251]
Hello,
Thanks for the great work! I wonder if anybody has experience whether this model can handle two crossing objects with same center, same size, but only different orientation (see the image below).

![IMG_0136](https://user-images.githubusercontent.com/11760870/77419009-affffa80-6e02-11ea-98ed-224b04b6b20a.jpeg)

In an anchor-based network, this problem can be solved by the anchor boxes with different aspect ratios. In FCOS, is this problem causing missed detection?

Thank you!

**Comment by tianzhi0549** [comment]
@wuyuanyi135 it is indeed a problem of the anchor-free detector. You might handle the case by the idea in "Matrix Nets: A New Deep Architecture for Object Detection".

**Comment by wuyuanyi135** [comment]
@tianzhi0549 Thanks for confirming this and your recommendation!

**Comment by tianzhi0549** [comment]
@wuyuanyi135 by the way, this does not imply that FCOS will fail to detect the two objects because there are many other locations in non-overlapped regions, which can be used to detect the box.

**Comment by wuyuanyi135** [comment]
@tianzhi0549 Understood. I will report back after I use it on my dataset. Thanks!
