### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by Dawn-LX** [tianzhi0549/FCOS#254]
I train FCOS  using 2 gpus, i think my gpu memory is enough , I can successfully train other projects with this 2gpus (e.g. CornerNet-Lite)
but it out of memory (I set batch_size == 8), there is  `nvidia-smi` information:
![image](https://user-images.githubusercontent.com/48169011/77839759-3aa17a80-71b2-11ea-9723-53ac0b0ec0d3.png)

the memory of gpu0 is partially used by my colleague, 
I also have tried only use gpu1 (also set batch size ==8), but still cuda out of memory

again, i think my gpu memory is enough. i can successfully train other projects with this 2gpus (e.g. CornerNet-Lite)
maybe FCOS does need more gpu memory?  Or is there any other hyperparameter which i can change to make my FCOS run successfully ?

Looking forward to your answer, thank you!

**Comment by Dawn-LX** [comment]
when batch size ==8, does it mean that each gpu afford 4?  can they be unequal and how ?

**Comment by tianzhi0549** [comment]
@Dawn-LX if you use the default input size (e.g., 800), one of your GPU cards can fit 4 images at most.

**Comment by Dawn-LX** [comment]
> @Dawn-LX if you use the default input size (e.g., 800), one of your GPU cards can fit 4 images at most.

Thank you , Is this evenly distributed between 2 gpus? Or does it adjust automatically? or whether i can set 4 images for one gpu and 2 images for another ?

**Comment by tianzhi0549** [comment]
@Dawn-LX It is evenly distributed.

**Comment by Dawn-LX** [comment]
> @Dawn-LX It is evenly distributed.

Thank you very much !
