### ISSUE TITLE
The reason why fine-tuning BN parameters of MobileNetV2

### ISSUE THREAD

**Issue by andgitchang** [tianzhi0549/FCOS#256]
Hi,
I am wondering the reason why used FrozenBN in ResNe(X)t configs, and instead adopting SyncBN to fine-tune BN params in MobileNetV2 settings? Does it due to the overall performance reason? If yes, then what makes the poor results?
Another question is that: comparison with other SyncBn configs in MobileNetV2 section, does FCOS_bn_bs16_MNV2_FPN_1x mean that it used FrozenBn throughout the backbone? Many thanks.

**Comment by tianzhi0549** [comment]
@andgitchang We follow the convention we froze the BN of ResNets. You can try to update them and it might result in improved performance. IIRC, for MobileNet-based modes, we always update the BN.

**Comment by andgitchang** [comment]
Thanks for your quick reply. To my second question, the config file FCOS_bn_bs16_MNV2_FPN_1x didn't adopt SyncBN. It implies that you updated BN params upon 2 imgs/gpu, inducing AP degradation concerns of small mini-batch size. So I raise this issue to confirm implementation details. It matters to my use case since I am lack of GPUs to adopt SyncBN setting :(

**Comment by tianzhi0549** [comment]
@andgitchang yes. This model updates BN with the images on the same GPU.

**Comment by andgitchang** [comment]
Ok then. It is interesting that small mini-batch size regime gets competitive AP performance as well. Thanks for your kind explanations.
