### ISSUE TITLE
centerness weighted bbox IoU loss

### ISSUE THREAD

**Issue by hyz-xmaster** [tianzhi0549/FCOS#271]
Hi @tianzhi0549, thanks for building this great detector. 

I noticed that,  when computing [the bbox's IoU loss](https://github.com/tianzhi0549/FCOS/blob/5fd728bfea150359fae28acb527e6e89d43c27e3/fcos_core/modeling/rpn/fcos/loss.py#L268-L271), it is weighted by the centerness target. 
What's the consideration of this weighting? Without this weighting, what about the performance?

Thank you.

**Comment by tianzhi0549** [comment]
@hyz-xmaster sorry about this late reply. We think the locations far from centres should have less weight during training because most of them will be removed by NMS. But in fact, this weight does not affect the final performance on COCO.

**Comment by hyz-xmaster** [comment]
Thanks for the reply. Got it.
