### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by wzj5133329** [tianzhi0549/FCOS#276]
when I  run the python setup.py build develop --no-deps
some errors happened,
show error: identifier "AT_CHECK" is undefined 。do you know where the problem is?

**Comment by tianzhi0549** [comment]
@wzj5133329 Can you post your PyTorch version?

**Comment by wzj5133329** [comment]
> @wzj5133329 Can you post your PyTorch version?
PyTorch:1.5.0

**Comment by wzj5133329** [comment]
> @wzj5133329 Can you post your PyTorch version?

pytorch version could cause this problem?

**Comment by tianzhi0549** [comment]
@wzj5133329 Please try `pytorch==1.3.1` instead, or you can replace `AT_CHECK` with `TORCH_CHECK`.

**Comment by wzj5133329** [comment]
> @wzj5133329 Please try `pytorch==1.3.1` instead, or you can replace `AT_CHECK` with `TORCH_CHECK`.

I have try this way :replace AT_CHECK with TORCH_CHECK ,now it compile success!Thanks a lot !

**Comment by Leslie0115** [comment]
@wzj5133329 I have encountered problems with pytorch 1.5, and it is completely OK after changing to 1.4.

**Comment by wzj5133329** [comment]
> @wzj5133329 I have encountered problems with pytorch 1.5, and it is completely OK after changing to 1.4.
oh,Thank you for helping me. it is ok now by replace AT_CHECK with TORCH_CHECK，I think the two ways both work ! I will close the issue.
