### ISSUE TITLE
配置环境遇到的坑——已跑通

### ISSUE THREAD

**Issue by gittigxuy** [tianzhi0549/FCOS#3]
目前mask rcnn benchmark仅仅支持pytorch==1.0.0版本，而不支持最新的pytorch1.0.1的版本，因此不能使用conda安装，而应该使用pip install torch==1.0.0。
然后还有一个就是，需要指定path_category.py里面的DATA_DIR的全路径，否则会因为找不到json文件而报错

**Comment by mama110** [comment]
可以用win10跑吗？

**Comment by ausk** [comment]
修改 `paths_catalog`： `maskrcnn_benchmark\config\paths_catalog.py`

**Comment by chiputao0823** [comment]
> 目前mask rcnn benchmark仅仅支持pytorch==1.0.0版本，而不支持最新的pytorch1.0.1的版本，因此不能使用conda安装，而应该使用pip install torch==1.0.0。
> 然后还有一个就是，需要指定path_category.py里面的DATA_DIR的全路径，否则会因为找不到json文件而报错
请问是怎么跑通的呢，按照readme直接train会找不到各种模块

**Comment by ausk** [comment]
It works on Win10 + Python 3.7 + Pytorch 1.0.1 + Cuda10.1. 
[Create inference_single_cvimage.py to inference on the single image.]https://github.com/tianzhi0549/FCOS/pull/5)

**Comment by tianzhi0549** [comment]
@chiputao0823 Please make sure you have installed all dependencies properly.

**Comment by mama110** [comment]
Please can you tell me any detail about installation, thanks.
@ausk
