### ISSUE TITLE
training doesn't cost time

### ISSUE THREAD

**Issue by 1ewandovski** [tianzhi0549/FCOS#30]
during my training , there was no error but total training time is 0 s.  i'm sure my environment is correct. here is some related information:

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pre_train/mymodel.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TRAIN: ("coco_2019_train","coco_2019_val")
  TEST: ("coco_2019_test","coco_2019_val")
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 1200
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (2400, 6000)
  MAX_ITER: 12000
  IMS_PER_BATCH: 1
  WARMUP_METHOD: "constant"

DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
DATASETS:
  TEST: ('coco_2019_test', 'coco_2019_val')
  TRAIN: ('coco_2019_train', 'coco_2019_val')
INPUT:
  MAX_SIZE_TEST: 1200
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_RANGE_TRAIN: (-1, -1)
  MIN_SIZE_TEST: 400
  MIN_SIZE_TRAIN: (400,)
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: True

  FCOS:
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    NMS_TH: 0.6
    NUM_CLASSES: 3
    NUM_CONVS: 4
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
  FCOS_ON: True

  WEIGHT: pre_train/mymodel.pth
OUTPUT_DIR: ./experiments/result
PATHS_CATALOG: /home/user/cocoapi/PythonAPI/maskrcnn_FCOS/FCOS/maskrcnn_benchmark/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 2000
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  MAX_ITER: 12000
  MOMENTUM: 0.9
  STEPS: (2400, 6000)
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: constant
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
TEST:
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 1

2019-05-05 18:30:27,756 maskrcnn_benchmark.trainer INFO: Start training
2019-05-05 18:30:27,852 maskrcnn_benchmark.trainer INFO: Total training time: 0:00:00.095197 (0.0000 s / it)
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2019-05-05 18:30:27,883 maskrcnn_benchmark.inference INFO: Start evaluation on coco_2019_test dataset(127 images)

**Comment by tianzhi0549** [comment]
@1ewandovski It seems that the training ends very quickly. Can you check your dataset? I guess your dataset contains no images or none of the images is read successfully.

**Comment by 1ewandovski** [comment]
@tianzhi0549 I've checked my dataset and didn't find any problem with it. Actually, during evaluation, "coco_2019_val" can be load correctly,which also used for training. 
By the way, I can train on these datasets with config-file "e2e_mask_rcnn_R_50_FPN_1x.yaml"

 
INFO: Start evaluation on coco_2019_val dataset(121 images).
100%|????????????????????????????????????????????????| 121/121 [00:04<00:00, 25.15it/s]
2019-05-05 21:45:29,280 maskrcnn_benchmark.inference INFO: Total run time: 0:00:04.816332 (0.039804397535718176 s / img per device, on 1 devices)
2019-05-05 21:45:29,281 maskrcnn_benchmark.inference INFO: Model inference time: 0:00:04.087672 (0.03378241121276351 s / img per device, on 1 devices)
2019-05-05 21:45:29,306 maskrcnn_benchmark.inference INFO: Preparing results for COCO format
2019-05-05 21:45:29,306 maskrcnn_benchmark.inference INFO: Preparing bbox results
2019-05-05 21:45:29,307 maskrcnn_benchmark.inference INFO: Evaluating predictions
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.06s).
Accumulating evaluation results...
DONE (t=0.02s).

**Comment by tianzhi0549** [comment]
@1ewandovski Probably because pre_train/mymodel.pth`  contains the iteration number. Therefore, the training finishes immediately since the iteration is initialized by the iteration stored in the model. Please try to manually remove `iteration` in the model with `torch.load()` and `torch.save()` APIs.

**Comment by 1ewandovski** [comment]
@tianzhi0549 thank you very much! i've solved the problem after remove iteration. i'll close the issue.
