### ISSUE TITLE
if center_x[..., 0].sum() == 0: IndexError: index 0 is out of bounds for dimension 1 with size 0

### ISSUE THREAD

**Issue by pp00704831** [tianzhi0549/FCOS#320]
Hello,

I train with my own datasets, and I have changed my data into coco-style, and I also remove the data without annotations too.
But I still encounter the problem like below:
![image](https://user-images.githubusercontent.com/57279608/102364501-7a82e900-3ff1-11eb-9578-297de1785dac.png)

My images are with maximum size = 800 and minimal size= 144.
Does anyone encounter this problem before?

**Comment by tianzhi0549** [comment]
@pp00704831 This might be because your objects are too small and thus there are no positive samples.

**Comment by pp00704831** [comment]
But there are still some bounding boxes in these objects.
Where should I modify the code to let small objects still have positive samples?
Thank you very much for your reply!
