### ISSUE TITLE
If I use other backbone to train rather than fcos_imprv_R_50_FPN_1x, I need to change something for inference?

### ISSUE THREAD

**Issue by pp00704831** [tianzhi0549/FCOS#323]
Hello, 
I use fcos_imprv_R_50_FPN_1x as a backbone network for my own datasets, it can work successfully for training and testing like below:
![image](https://user-images.githubusercontent.com/57279608/103283680-31c92800-4a14-11eb-8437-74e60251ac23.png)

But when I use other backbones such as  fcos_imprv_R_101_FPN_1x or fcos_imprv_dcnv2_R_50_FPN_1x, it can train successfully because its loss value will decline gradually.
![image](https://user-images.githubusercontent.com/57279608/103284506-5de5a880-4a16-11eb-9bef-86a96a86f637.png)

But when I use inference code " python tools/test_net.py --config-file configs/fcos/fcos_imprv_dcnv2_R_50_FPN_1x.yaml 
MODEL.WEIGHT ./training_dir/fcos_imprv_dcnv2_R_50_FPN_1x/model_0027500.pth " for other backbones rather than fcos_imprv_R_50_FPN_1x, it will get zero value for all AP
![image](https://user-images.githubusercontent.com/57279608/103284257-b36d8580-4a15-11eb-8a43-5b0fae539196.png)

Because it can be successfully trained, as shown above. Do I need to change something for testing with other backbones rather than  fcos_imprv_R_50_FPN_1? I have already change the --config-file and MODEL.WEIGHT.

**Comment by tianzhi0549** [comment]
@pp00704831 It seems your model is different from the one during training. Please check all the weights are successfully loaded during testing.

**Comment by pp00704831** [comment]
Hello,
But I just used your training codes, and your training and testing command, the training weights will be saved at ./training_dir/fcos_imprv_dcnv2_R_50_FPN_1x. The most strange thing is that only fcos_imprv_R_50_FPN_1x can be successfully tested @@, others will show 0 AP value. I am keeping trying training on other backbones to check if this situation will keep occurring.
