### ISSUE TITLE
What is scale in class FCOSHead in focs.py?

### ISSUE THREAD

**Issue by lg920810** [tianzhi0549/FCOS#33]
I have a question that why init_value in scale is 1.0 and why need do 5 iters?
See the code in focs.py is  self.scales = nn.ModuleList([Scale(init_value=1.0) for _ in range(5)])

**Comment by tianzhi0549** [comment]
@lg920810 Please refer to the last paragraph in section 3.2 in our paper. https://arxiv.org/pdf/1904.01355.pdf

**Comment by lg920810** [comment]
> @lg920810 Please refer to the last paragraph in section 3.2 in our paper. https://arxiv.org/pdf/1904.01355.pdf

Thank you very much. I had thought the scale is a constant, but now I understand that it can be trained.
