### ISSUE TITLE
can't import _C

### ISSUE THREAD

**Issue by cvJie** [tianzhi0549/FCOS#353]
![微信图片_20210720085125](https://user-images.githubusercontent.com/31844043/126245835-ce04ac35-4a75-4db5-851e-2c25e9fa1944.png)

I can't import  _C,and can't find _C in fcos_sore,so i change it to import _C from ._utils，but it still error.
can you give me some advices?

code from :
  #from ._utils import _C
  from fcos_core import _C
to:
  from ._utils import _C
  #from fcos_core import _C

**Comment by guigarfr** [comment]
You should compile C code.

run `python setup.py develop` in the project directory or `python setup.py develop --no-deps`

**Comment by student123ab** [comment]
> You should compile C code.
> 
> run `python setup.py develop` in the project directory or `python setup.py develop --no-deps`

I run the file but report an error " RuntimeError: Error compiling objects for extension " could you help me, thanks
