### ISSUE TITLE
/FCOS/maskrcnn_benchmark/layers

### ISSUE THREAD

**Issue by qianzhang2018** [tianzhi0549/FCOS#38]
#from maskrcnn_benchmark import _C
from ._utils import _C

i use "from ._utils import _C" instead of "from maskrcnn_benchmark import _C" in roi_align.py,roi_pool.py

is it right?
I modified this way.it works now,but i do not know it right?

**Comment by tianzhi0549** [comment]
@qianzhang2018 If it works well, I think it should be right.
