### ISSUE TITLE
How to resume training？

### ISSUE THREAD

**Issue by ZhengMengbin** [tianzhi0549/FCOS#39]
How to resume training？ I see that there is no part of the code to resume training, they are all trained from scratch. But if the program is interrupted unexpectedly, how can I resume training?

**Comment by ZhengMengbin** [comment]
How to resume training？ I see that there is no part of the code to resume training, they are all trained from scratch. But if the program is interrupted unexpectedly, how can I resume training?

**Comment by tianzhi0549** [comment]
@ZhengMengbin Just run the training script again with the same arguments. It will resume the training if there is a checkpoint.

**Comment by ZhengMengbin** [comment]
@tianzhi0549 Yes, but when I test, it will also using the checkpoint to test, can not test other epoch's result(.pth).

**Comment by tianzhi0549** [comment]
@ZhengMengbin If you want to test another checkpoint, you need to specify `MODEL.WEIGHT`.  Please refer to https://github.com/tianzhi0549/FCOS/blob/master/README.md#inference.

**Comment by ZhengMengbin** [comment]
Thanks for your reply, I had fixed this bug last week, specifying 'MODEL.WEIGHT' do not help owing to the load() function in checkpoint.py, I modified the code as follows:
![image](https://user-images.githubusercontent.com/26650043/60488319-3eac7480-9cd4-11e9-9df3-f8149879c94c.png)

**Comment by tianzhi0549** [comment]
@ZhengMengbin That's great!
