### ISSUE TITLE
How to inference on single image

### ISSUE THREAD

**Issue by jinfagang** [tianzhi0549/FCOS#4]
Does there any scripts test on single image? So coupled with maskrcnn-benchmark, I can not even find out where the whole pipeline of FCOS exists

**Comment by tianzhi0549** [comment]
FCOS’ core code is located at https://github.com/tianzhi0549/FCOS/tree/master/maskrcnn_benchmark/modeling/rpn/fcos . We will add the single image inference script in a few days. Thank you.

**Comment by ausk** [comment]
This pull do the work: [Create inference_single_cvimage.py to inference on the single image. #5](https://github.com/tianzhi0549/FCOS/pull/5)
You can try to use the file `demo/inference_single_cvimage.py` to inference on single opencv image.
