### ISSUE TITLE
About the head feature sharing 

### ISSUE THREAD

**Issue by Angzz** [tianzhi0549/FCOS#44]
Hi, dose the head features for cls and box (e.g. 4 * conv) shared in your implementation? have you experimented to compare the difference for the final performance?

**Comment by tianzhi0549** [comment]
@Angzz Following RetinaNet, we do not share 4 convolutional layers between cls and bbox. We did not experiment the one sharing these layers, but it should drop the performance a lot.

**Comment by Angzz** [comment]
thanks, I am reproducing your result with mxnet-gluon, but it still have two points below, I am looking into this.

**Comment by Angzz** [comment]
By the way, RetinaNet in original paper shares these features.

**Comment by Angzz** [comment]
Sorry, It seems that you misunderstand my words, I mean that does the 4 * conv features for cls(or box) in different fpn layers shared  in your implementation?

**Comment by tianzhi0549** [comment]
@Angzz Sorry about that. They are shared between different FPN levels. Do you have a RetinaNet implemented in mxnet-gluon? I think it would be a good start for implementing our detector.
