### ISSUE TITLE
what is the final loss?

### ISSUE THREAD

**Issue by JinLingChristopher** [tianzhi0549/FCOS#45]
I am training the mode on my own dataset, and I also modified some part of the code.

Could you tell me, what is the final value of each loss of your model? About cls_loss, reg_loss, centerness_loss.  This might be helpful for me to check my training procedure and related code.

Thanks.

**Comment by tianzhi0549** [comment]
@JinLingChristopher The final loss (when iteration = 90000) for R-50 model are as follow,
total_loss: 1.0017 loss_cls: 0.1772 loss_centerness: 0.5846 loss_reg: 0.2439.

**Comment by JinLingChristopher** [comment]
> @JinLingChristopher The final loss (when iteration = 90000) for R-50 model are as follow,
> total_loss: 1.0017 loss_cls: 0.1772 loss_centerness: 0.5846 loss_reg: 0.2439.

Thank you so much !
