### ISSUE TITLE
_C.cpython-37m-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by fengfengfeng96** [tianzhi0549/FCOS#51]
Hi,
I followed the instructions to create an environment FCOS，every package installed successfully.

after running:

wget https://cloudstor.aarnet.edu.au/plus/s/dDeDPBLEAt19Xrl/download -O FCOS_R_50_FPN_1x.pth
python demo/fcos_demo.py

erorr happens:

ImportError: /home/XX/FCOS/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_30E

thank you.

**Comment by tianzhi0549** [comment]
@fengfengfeng96 Please make sure you used the same Python environments when compiling and running.

**Comment by fengfengfeng96** [comment]
https://github.com/facebookresearch/maskrcnn-benchmark/issues/421
Try rm -rf build and then compiling it again：、
cd FCOS
rm -rf build
python setup.py build develop
