### ISSUE TITLE
where is inference_single_cv.py file ?

### ISSUE THREAD

**Issue by JinLingChristopher** [tianzhi0549/FCOS#52]
I read issues and know the existence of the file "inference_single_cv.py", but I cannot find it in the code base. what is the path of that file?

**Comment by tianzhi0549** [comment]
@JinLingChristopher Please use `demo/fcos_demo.py` instead.

**Comment by tengerye** [comment]
@tianzhi0549 Why every class requires cfg as parameter, which makes it hard to reuse.
