### ISSUE TITLE
Is the range of target size related to the stride for a specific level

### ISSUE THREAD

**Issue by LouieYang** [tianzhi0549/FCOS#53]
Is the range of size related to the stride for a specific level? And is it possible to set p3 < 64, p4 ~ [64, 128], p5 ~[128, 256], p6 ~ [256, inf] for customized dataset?

Many thanks.

**Comment by tianzhi0549** [comment]
@LouieYang The sizes not related to other settings. You can change them according to your dataset.

**Comment by LouieYang** [comment]
Thanks and close it.
