### ISSUE TITLE
600ms on mx150 which is slow

### ISSUE THREAD

**Issue by jinfagang** [tianzhi0549/FCOS#56]
I can run yolov3 mobilenet on my laptop which has mx150 2G GPU memory and CUDA10 with 30fps.

But FCOS runs 600ms!  Which is far way from realtime and really slow!

Does there any speed inference on gtx1080 ti? how's the speed on that? I don't know why it is slow

**Comment by tianzhi0549** [comment]
@jinfagang Do you use the same backbone for FCOS and YOLOv3?

**Comment by jinfagang** [comment]
@tianzhi0549  No, but 600ms is really intolerable slow since even SSD with a heavy backbone can achieve less than 100ms/frame on GPU.

**Comment by tianzhi0549** [comment]
Can you try to use smaller input size?

**Comment by jinfagang** [comment]
@tianzhi0549  Which model is lightest amongest all of FCOS pretrained model? I can test the lightest model.

**Comment by tianzhi0549** [comment]
@jinfagang It is now R-50, but we may release light-weight models later.

**Comment by ChangErgou** [comment]
Honestly, the SSD does not have FPN architecture and shows limited performance. And the FCOS works well on stronger GPU. In addition, the inference speed is not the only metric for an object detector. Maybe, you should buy a stronger GPU.

**Comment by jinfagang** [comment]
@ChangErgou  I have Titan on training, however for production purpose, it's not wise enough to inference using Titan everywhere..

**Comment by ChangErgou** [comment]
I have gtx1080 for training and inference. changzhonghan16 Email:changzhonghan16@mails.ucas.ac.cn Signature is customized by Netease Mail Master On 06/03/2019 10:15, JinTian wrote: @ChangErgou I have Titan on training, however for production purpose, it's not wise enough to inference using Titan everywhere.. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jinfagang** [comment]
@ChangErgou @tianzhi0549  I have a GTX1080TI now using R_50 model got this speed:

```
INFO 06-05 09:53:04 simpler_predictor.py:37 - using device: cuda
COCO_val2014_000000000885.jpg	inference time: 0.10s
COCO_val2014_000000001000.jpg	inference time: 0.11s
COCO_val2014_000000005477.jpg	inference time: 0.11s
COCO_val2014_000000007281.jpg	inference time: 0.11s
COCO_val2014_000000012639.jpg	inference time: 0.09s
COCO_val2014_000000033759.jpg	inference time: 0.09s
COCO_val2014_000000039769.jpg	inference time: 0.09s
COCO_val2014_000000050896.jpg	inference time: 0.08s
COCO_val2014_000000053505.jpg	inference time: 0.10s
COCO_val2014_000000128654.jpg	inference time: 0.09s
COCO_val2014_000000463842.jpg	inference time: 0.09s
COCO_val2014_000000479030.jpg	inference time: 0.10s
Press any keys to exit ...

```

100ms, slightly slow

**Comment by tianzhi0549** [comment]
@jinfagang By default, the input image is resized to have its shorter side being 800. If you only pursuit fast inference, I suggest that you use a smaller input size such as 512 by running `python demo/fcos_demo.py --min-image-size 512`.
