### ISSUE TITLE
CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by mengxzh15** [tianzhi0549/FCOS#59]
i compile the FCOS, but it give me the error like this. i run it on ubuntu16.04,and my cuda version is 10.0,i dont  know how to operate it correctly. if  someone give me some instructions ,i very very very thanks to you.

**Comment by tianzhi0549** [comment]
@mengxzh15 Please make sure you have installed `g++`.
