### ISSUE TITLE
coco path

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#61]
I meet this error when I'm trying to train the coco dataset:

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2014.json'

Where can I modify the path of coco dataset?

P.s. my coco dataset path is /home/kun/dataset/MSCOCO2014

**Comment by tianzhi0549** [comment]
@mama110 Please follow the instructions in *Perform training on COCO dataset* in https://github.com/tianzhi0549/FCOS/blob/master/MASKRCNN_README.md.

**Comment by mama110** [comment]
Thanks.@tianzhi0549

**Comment by 66mengyu** [comment]
hello,when I use the gempy to load the data,the data files and code file in the one ,but all the time happen the following errors. 
code:geo_data = gp.create_data(extent = [0,1000,0,1000,0,1000], 
                          resolution = [50, 50, 50],
                          path_o = 'model1_orientations.csv',
                          path_i = 'model1_surface_points.csv')
errors:
  File "D:\anaconda\install\lib\site-packages\pandas\io\common.py", line 707, in get_handle
    newline="",

FileNotFoundError: [Errno 2] No such file or directory: 'model1_surface_points.csv'
why?please help me.
