### ISSUE TITLE
when I fit the code to my dataset, all the losses are nan other than first 20 iterations

### ISSUE THREAD

**Issue by hdjsjyl** [tianzhi0549/FCOS#63]
Thanks for your excellent code. When I fit the code to my dataset, all the losses are nan other than first 20 iterations. Any advice will be appreciated, thanks

**Comment by tianzhi0549** [comment]
@hdjsjyl Please refer to this issue https://github.com/tianzhi0549/FCOS/issues/6#issuecomment-483491988.

**Comment by hdjsjyl** [comment]
@tianzhi0549   Thanks a lot. I am a newer of pytorch and I have another question. I want to use one GPU in the cluster, the GPU I want to use is the third one. How to set it in the code? Thanks

**Comment by tianzhi0549** [comment]
You can use export CUDA_VISIBLE _DEVICES=“2” before running the command line.

**Comment by hdjsjyl** [comment]
@tianzhi0549  Thanks, I finished this problem. When I use two gpus to train fcos on my own dataset, it still gets nan. Any advice will be appreciated, thanks

**Comment by tianzhi0549** [comment]
@hdjsjyl Can you try to use larger batch size?
