### ISSUE TITLE
 Problem about size mismatch.

### ISSUE THREAD

**Issue by jsjs0827** [tianzhi0549/FCOS#65]
I try to run the demo/fcos_demo,but size mismatch occurs.
I use the default setting in the fcos_demo,config-file:configs/fcos/fcos_R_50_FPN_1x.yaml;
weights:FCOS_R_50_FPN_1x.pth.
The difinite description is below:
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
size mismatch for rpn.head.cls_logits.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([15]).
	size mismatch for rpn.head.cls_logits.weight: copying a param with shape torch.Size([80, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([15, 256, 1, 1]).
	size mismatch for rpn.head.bbox_pred.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([60]).
	size mismatch for rpn.head.bbox_pred.weight: copying a param with shape torch.Size([4, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([60, 256, 1, 1]).
What should I do?

**Comment by tianzhi0549** [comment]
@jsjs0827 Did you change the code?

**Comment by jsjs0827** [comment]
No. Can you give any suggestion？
