### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by heiyuxiaokai** [tianzhi0549/FCOS#70]
File "/home/fw/Softwares/FCOS/maskrcnn_benchmark/structures/boxlist_ops.py", line 84, in boxlist_iou
    wh = (rb - lt + TO_REMOVE).clamp(min=0)  # [N,M,2]
RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB (GPU 1; 11.92 GiB total capacity; 7.99 GiB already allocated; 1.20 GiB free; 1.74 GiB cached)

It seems the iou caculate' problem. I use retinanet, batch 4, 2 titan x(12G)
The GPU use of beginning:
![Screenshot from 2019-06-23 10-40-26](https://user-images.githubusercontent.com/27018045/59970875-5e8cbb80-95a3-11e9-83c2-742ef0a68377.png)
Should I set the batch to 2?

**Comment by tianzhi0549** [comment]
@heiyuxiaokai Did FCOS run out of memory?

**Comment by heiyuxiaokai** [comment]
@tianzhi0549 No，Maybe the iou caculate process of a special image（with many boxes） need a lot of memory. FCOS haven't this process. Did your GPU is 12G where you train this model for (4 gpu, batch 8)?
The data I use is remote sensing image, which may have many object.

**Comment by tianzhi0549** [comment]
@heiyuxiaokai our GPUs are 32GB V100.

**Comment by heiyuxiaokai** [comment]
@tianzhi0549 So I should set batch to 2. You train batch 8 of 4 GPU(V100). Why don't you use a larger batch for 32g GPU?

**Comment by tianzhi0549** [comment]
@heiyuxiaokai We use 16 images in a mini-batch for a fair comparison.

**Comment by heiyuxiaokai** [comment]
Too many GT Boxes. It was explained there. 
https://github.com/facebookresearch/maskrcnn-benchmark/issues/18

**Comment by heiyuxiaokai** [comment]
@dreamhighchina Reference there: https://github.com/facebookresearch/maskrcnn-benchmark/issues/884
