### ISSUE TITLE
A question about IOUloss

### ISSUE THREAD

**Issue by ZhengMengbin** [tianzhi0549/FCOS#72]
Why add 1.0 not a very small number when calculating IOUloss?
![WeChat67d0afadf9a3a7d7941fd121a54c9963](https://user-images.githubusercontent.com/26650043/60065207-a3e0f280-9735-11e9-9024-3dd7b33e17f6.png)

**Comment by tianzhi0549** [comment]
@ZhengMengbin They prevent the denominator from being too small. The 1 in the numerator is used to keep the maximal loss being 1.
