### ISSUE TITLE
how to set multiple regression levels for smaller image size?

### ISSUE THREAD

**Issue by liwei46** [tianzhi0549/FCOS#76]
Hello, 

Thanks for the great work.  
In the default setting, the image size is 1333*800, and multiple level are set 0, 64, 128, 256, 512 for feature maps with strides 8, 16, 32, 64 and 128. 

I am wondering for smaller image, lets say 224*224, how to set the multiple level? 

Are there some simple equation to set this base on image size. 
Thanks.

**Comment by tianzhi0549** [comment]
@liwei46 you can try to make them roughly proportional to the image size.

**Comment by liwei46** [comment]
@tianzhi0549  Thanks.
