### ISSUE TITLE
About using syncbn.

### ISSUE THREAD

**Issue by bearcatt** [tianzhi0549/FCOS#77]
I think we should set broadcast_buffers to cfg.MODEL.USE_SYNCBN [here](https://github.com/tianzhi0549/FCOS/blob/928c610dbae256242a2514fe212f9b10cc6fe0fc/tools/train_net.py#L47) since the BatchNorm stats should be updated if we want to use SyncBN.

**Comment by tianzhi0549** [comment]
@bearcatt Thank you for pointing it out. I do not test it by myself but it probably has no effect on the final performance. Anyway, I will test it.
