### ISSUE TITLE
win10+anaconda 

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#8]
Does FCOS support win10?

**Comment by tianzhi0549** [comment]
We don’t test it on win10, but we think it should work well on windows. Just try it.

**Comment by mama110** [comment]
There is a problem about "cl.exe" when I run setup.py, the logs are as follows:

(F:\Anaconda3\envs\driedfish) F:\FCOS-master>python setup.py build develop
running build
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\maskrcnn_benchmark
copying maskrcnn_benchmark\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\config
copying maskrcnn_benchmark\config\defaults.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\config
copying maskrcnn_benchmark\config\paths_catalog.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\config
copying maskrcnn_benchmark\config\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\config
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data
copying maskrcnn_benchmark\data\build.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data
copying maskrcnn_benchmark\data\collate_batch.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data
copying maskrcnn_benchmark\data\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\engine
copying maskrcnn_benchmark\engine\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\engine
copying maskrcnn_benchmark\engine\trainer.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\engine
copying maskrcnn_benchmark\engine\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\engine
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\batch_norm.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\iou_loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\misc.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\nms.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\roi_align.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\roi_pool.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\scale.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\sigmoid_focal_loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\smooth_l1_loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\_utils.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
copying maskrcnn_benchmark\layers\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\layers
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\balanced_positive_negative_sampler.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\box_coder.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\make_layers.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\matcher.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\poolers.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\registry.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\utils.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
copying maskrcnn_benchmark\modeling\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\solver
copying maskrcnn_benchmark\solver\build.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\solver
copying maskrcnn_benchmark\solver\lr_scheduler.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\solver
copying maskrcnn_benchmark\solver\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\solver
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
copying maskrcnn_benchmark\structures\bounding_box.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
copying maskrcnn_benchmark\structures\boxlist_ops.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
copying maskrcnn_benchmark\structures\image_list.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
copying maskrcnn_benchmark\structures\keypoint.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
copying maskrcnn_benchmark\structures\segmentation_mask.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
copying maskrcnn_benchmark\structures\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\structures
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\c2_model_loading.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\checkpoint.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\collect_env.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\comm.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\cv2_util.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\env.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\imports.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\logger.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\metric_logger.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\miscellaneous.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\model_serialization.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\model_zoo.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\registry.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\timer.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
copying maskrcnn_benchmark\utils\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\utils
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets
copying maskrcnn_benchmark\data\datasets\coco.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets
copying maskrcnn_benchmark\data\datasets\concat_dataset.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets
copying maskrcnn_benchmark\data\datasets\list_dataset.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets
copying maskrcnn_benchmark\data\datasets\voc.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets
copying maskrcnn_benchmark\data\datasets\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data\samplers
copying maskrcnn_benchmark\data\samplers\distributed.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\samplers
copying maskrcnn_benchmark\data\samplers\grouped_batch_sampler.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\samplers
copying maskrcnn_benchmark\data\samplers\iteration_based_batch_sampler.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\samplers
copying maskrcnn_benchmark\data\samplers\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\samplers
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data\transforms
copying maskrcnn_benchmark\data\transforms\build.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\transforms
copying maskrcnn_benchmark\data\transforms\transforms.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\transforms
copying maskrcnn_benchmark\data\transforms\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\transforms
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation
copying maskrcnn_benchmark\data\datasets\evaluation\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation\coco
copying maskrcnn_benchmark\data\datasets\evaluation\coco\coco_eval.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation\coco
copying maskrcnn_benchmark\data\datasets\evaluation\coco\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation\coco
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation\voc
copying maskrcnn_benchmark\data\datasets\evaluation\voc\voc_eval.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation\voc
copying maskrcnn_benchmark\data\datasets\evaluation\voc\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\data\datasets\evaluation\voc
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\backbone.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\fbnet.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\fbnet_builder.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\fbnet_modeldef.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\fpn.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\resnet.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
copying maskrcnn_benchmark\modeling\backbone\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\backbone
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\detector
copying maskrcnn_benchmark\modeling\detector\detectors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\detector
copying maskrcnn_benchmark\modeling\detector\generalized_rcnn.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\detector
copying maskrcnn_benchmark\modeling\detector\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\detector
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads
copying maskrcnn_benchmark\modeling\roi_heads\roi_heads.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads
copying maskrcnn_benchmark\modeling\roi_heads\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
copying maskrcnn_benchmark\modeling\rpn\anchor_generator.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
copying maskrcnn_benchmark\modeling\rpn\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
copying maskrcnn_benchmark\modeling\rpn\loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
copying maskrcnn_benchmark\modeling\rpn\rpn.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
copying maskrcnn_benchmark\modeling\rpn\utils.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
copying maskrcnn_benchmark\modeling\rpn\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
copying maskrcnn_benchmark\modeling\roi_heads\box_head\box_head.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
copying maskrcnn_benchmark\modeling\roi_heads\box_head\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
copying maskrcnn_benchmark\modeling\roi_heads\box_head\loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
copying maskrcnn_benchmark\modeling\roi_heads\box_head\roi_box_feature_extractors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
copying maskrcnn_benchmark\modeling\roi_heads\box_head\roi_box_predictors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
copying maskrcnn_benchmark\modeling\roi_heads\box_head\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\box_head
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
copying maskrcnn_benchmark\modeling\roi_heads\keypoint_head\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
copying maskrcnn_benchmark\modeling\roi_heads\keypoint_head\keypoint_head.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
copying maskrcnn_benchmark\modeling\roi_heads\keypoint_head\loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
copying maskrcnn_benchmark\modeling\roi_heads\keypoint_head\roi_keypoint_feature_extractors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
copying maskrcnn_benchmark\modeling\roi_heads\keypoint_head\roi_keypoint_predictors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
copying maskrcnn_benchmark\modeling\roi_heads\keypoint_head\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\keypoint_head
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
copying maskrcnn_benchmark\modeling\roi_heads\mask_head\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
copying maskrcnn_benchmark\modeling\roi_heads\mask_head\loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
copying maskrcnn_benchmark\modeling\roi_heads\mask_head\mask_head.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
copying maskrcnn_benchmark\modeling\roi_heads\mask_head\roi_mask_feature_extractors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
copying maskrcnn_benchmark\modeling\roi_heads\mask_head\roi_mask_predictors.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
copying maskrcnn_benchmark\modeling\roi_heads\mask_head\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\roi_heads\mask_head
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\fcos
copying maskrcnn_benchmark\modeling\rpn\fcos\fcos.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\fcos
copying maskrcnn_benchmark\modeling\rpn\fcos\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\fcos
copying maskrcnn_benchmark\modeling\rpn\fcos\loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\fcos
copying maskrcnn_benchmark\modeling\rpn\fcos\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\fcos
creating build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\retinanet
copying maskrcnn_benchmark\modeling\rpn\retinanet\inference.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\retinanet
copying maskrcnn_benchmark\modeling\rpn\retinanet\loss.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\retinanet
copying maskrcnn_benchmark\modeling\rpn\retinanet\retinanet.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\retinanet
copying maskrcnn_benchmark\modeling\rpn\retinanet\__init__.py -> build\lib.win-amd64-3.6\maskrcnn_benchmark\modeling\rpn\retinanet
running build_ext
F:\Anaconda3\envs\driedfish\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'maskrcnn_benchmark._C' extension
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
creating build\temp.win-amd64-3.6\Release\FCOS-master
creating build\temp.win-amd64-3.6\Release\FCOS-master\maskrcnn_benchmark
creating build\temp.win-amd64-3.6\Release\FCOS-master\maskrcnn_benchmark\csrc
creating build\temp.win-amd64-3.6\Release\FCOS-master\maskrcnn_benchmark\csrc\cpu
creating build\temp.win-amd64-3.6\Release\FCOS-master\maskrcnn_benchmark\csrc\cuda
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IF:\FCOS-master\maskrcnn_benchmark\csrc -IF:\Anaconda3\envs\driedfish\lib\site-packages\torch\lib\include -IF:\Anaconda3\envs
\driedfish\lib\site-packages\torch\lib\include\torch\csrc\api\include -IF:\Anaconda3\envs\driedfish\lib\site-packages\torch\lib\include\TH -IF:\Anaconda3\envs\driedfish\lib\site-pac
kages\torch\lib\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IF:\Anaconda3\envs\driedfish\include -IF:\Anaconda3\envs\driedfish\include "-IF:\Mi
crosoft Visual Studio 14.0\VC\INCLUDE" "-IF:\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files
 (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program File
s (x86)\Windows Kits\8.1\include\\winrt" /EHsc /TpF:\FCOS-master\maskrcnn_benchmark\csrc\vision.cpp /Fobuild\temp.win-amd64-3.6\Release\FCOS-master\maskrcnn_benchmark\csrc\vision.ob
j -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
error: command 'cl.exe' failed: No such file or directory

**Comment by tianzhi0549** [comment]
It seems that you don’t install the compiler in your system.
