### ISSUE TITLE
Should I adjust area_ranges to the input size?

### ISSUE THREAD

**Issue by BlueBlueFF** [tianzhi0549/FCOS#81]
When I use small input size, should i change the area_ranges to input? or area_ranges only depends on the size of gt_boxes?

**Comment by tianzhi0549** [comment]
@BlueBlueFF Which `area_ranges` are you questioning? Could you post the code line number here?

**Comment by BlueBlueFF** [comment]
> @BlueBlueFF Which `area_ranges` are you questioning? Could you post the code line number here?

` area_ranges = [
        [0 ** 2, 1e5 ** 2],  # all
        [0 ** 2, 32 ** 2],  # small
        [32 ** 2, 96 ** 2],  # medium
        [96 ** 2, 1e5 ** 2],  # large
        [96 ** 2, 128 ** 2],  # 96-128
        [128 ** 2, 256 ** 2],  # 128-256
        [256 ** 2, 512 ** 2],  # 256-512
        [512 ** 2, 1e5 ** 2],
    ]  # 512-inf`
in FCOS/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py

**Comment by tianzhi0549** [comment]
@BlueBlueFF The area_ranges have nothing to do with the input size. They are defined with the original input size.

**Comment by BlueBlueFF** [comment]
> @BlueBlueFF The area_ranges have nothing to do with the input size. They are defined with the original input size.

Thanks a lot！
