### ISSUE TITLE
能问下怎么网络可视化？

### ISSUE THREAD

**Issue by qianzhang2018** [tianzhi0549/FCOS#84]
想看一下网络每一层参数

**Comment by qianzhang2018** [comment]
刚学习深度学习，想学习一下这个网络，论文看的不是很明确

**Comment by tianzhi0549** [comment]
@qianzhang2018 sorry, I am not familiar with network visualization with pytorch. Maybe this post can help you. https://discuss.pytorch.org/t/print-autograd-graph/692/2
