### ISSUE TITLE
About the input size

### ISSUE THREAD

**Issue by holyhao** [tianzhi0549/FCOS#9]
Tanks for your work, it is excellent. I have some puzzles. Do you have some experiments on smaller input size, like 300*300 or 224*224, how does the input size influence the final results? Also, the postprocessing of the locations need to the filtered with classification *center-ness score, then the filtered locations will be calculated back to bbox flowed by the NMS. How many bboxes averagely will be calculated back to bbox?  Does this operations with NMS cost much time? Looking forward to your reply.

**Comment by tianzhi0549** [comment]
Thank you for your questions. Because we have released both training and testing code, we suggest that you find the answers of these questions by yourself. We would appreciate it if you report you findings here.

**Comment by holyhao** [comment]
@tianzhi0549 Tanks for your reply,  since you did not have some expriments results about the above concerns. I will try some expriments.  The source code is really helpful and thansk for that. Hope to keep in touch about this.

**Comment by tianzhi0549** [comment]
@holyhao OK. Should you have any questions when doing these experiments, please be free to ask us here.
