### ISSUE TITLE
bounding box prediction

### ISSUE THREAD

**Issue by mama110** [tianzhi0549/FCOS#93]
Hello.
In your paper, you said "FCOS takes advantages of all points in a ground truth bounding box to predict the bounding boxes and the low-quality detected bounding boxes are suppressed
by the proposed “center-ness” branch". Can you please tell me the detail of that part or the related code? Thank you.

**Comment by tianzhi0549** [comment]
@mama110 Code related to FCOS is in https://github.com/tianzhi0549/FCOS/tree/master/maskrcnn_benchmark/modeling/rpn/fcos.
