### ISSUE TITLE
Do you have a plan for instance segmentation?

### ISSUE THREAD

**Issue by stigma0617** [tianzhi0549/FCOS#94]
Hi,

In your paper,

> "The proposed detector can be immediately extended to solve other vision tasks with minimal modification, including instance segmentation and key-point detection."

is described.

Do you have a plan to extend for instance segmentation such as Mask R-CNN ?

**Comment by tianzhi0549** [comment]
@stigma0617 We are working on instance segmentation now.

**Comment by stigma0617** [comment]
Cool !! 
Your work is very awesome!! good luck !

**Comment by tianzhi0549** [comment]
@stigma0617 Thank you.

**Comment by stigma0617** [comment]
@tianzhi0549 Congratulation for acception in ICCV'19. 

When do you expect the instance segmentation to be completed?

**Comment by tianzhi0549** [comment]
@stigma0617 Thank you for your congratulation. I can't give you a guarantee. We are trying some new ideas for instance segmentation (not only using maskrcnn), so I am not sure the time of completion.

**Comment by stigma0617** [comment]
@tianzhi0549 ,

Oh I see, I'm developing my new [VoVNet](https://github.com/stigma0617/maskrcnn-benchmark-vovnet/tree/vovnet) backbone in your FOCS. So I just wondered instance segmentation task.

my naive result(VoV57-FCOS) is [that](https://github.com/tianzhi0549/FCOS/issues/31#issuecomment-513060736)

Good luck

**Comment by tianzhi0549** [comment]
@stigma0617 Great work! Thank you very much for sharing your results and code.

**Comment by heng2j** [comment]
Hi @stigma0617, your results with VoVNet-FCOS, I’m wonder in your repository, will you also share about your insights of how to retain the model with your own dataset? And how’s the configuration should be for VoVNet?

**Comment by stigma0617** [comment]
@heng2j 
I trained VoVNet-FCOS on COCO dataset.  

The configuration of VoVNet-FCOS is same as [VoVNet-Detectron](https://github.com/stigma0617/maskrcnn-benchmark-vovnet).

**Comment by heng2j** [comment]
Hi @stigma0617.

Thank you for your replying! Like what you replied on the I am currently training a FCOS_PLUS model with my own dataset and used VoVNet57 as the backbone. 

I really want to see how well it perform on small objects.

**Comment by heng2j** [comment]
So after 82000 iterations, the AP are still very low. And the loss decays so slow as well.

**Comment by stigma0617** [comment]
@heng2j,
 I'll upload VoVNet-FCOS soon.

**Comment by heng2j** [comment]
Hi @stigma0617, thank you for the updates! Looking forward! At the meantime, I will stick with RestNet first for the baseline.

**Comment by stigma0617** [comment]
@heng2j , @tianzhi0549 

I upload the [VoVNet-FCOS project](https://github.com/vov-net/VoVNet-FCOS).

**Comment by heng2j** [comment]
Hi @stigma0617 , thank you so much for letting us know! Greatly Appreciated! I will take a look and post issue on your repo if I encountered any issue. Cheers!

**Comment by tianzhi0549** [comment]
@stigma0617 Thank you very much! I will add it into our README to let more people know this.

**Comment by stigma0617** [comment]
@tianzhi0549 
Thanks :)
