### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark.solver'

### ISSUE THREAD

**Issue by allenwangcheng** [tianzhi0549/FCOS#95]
when i run the demo in nas-fcos everything is ok,but once i move the training pyfile to nas-fcos，the problem happens,I comfused about the maskrcnn-benchmark installlation. expect your reply ,thank you

**Comment by tianzhi0549** [comment]
@allenwangcheng Are you sure you install the project correctly?

**Comment by allenwangcheng** [comment]
I am not sure,I joust follow the install md  in nas-fcos，but I confuse the maskrcnn_benchmark dir in it ,




| |
王程
|
|
邮箱：allenwangcheng@163.com
|

签名由 网易邮箱大师 定制

On 07/19/2019 18:59, Tian Zhi wrote:

@allenwangcheng Are you sure you install the project correctly?

**Comment by allenwangcheng** [comment]
Can I follow your wechat,heihei




| |
王程
|
|
邮箱：allenwangcheng@163.com
|

签名由 网易邮箱大师 定制

On 07/20/2019 01:10, allenwangcheng wrote:
I am not sure,I joust follow the install md  in nas-fcos，but I confuse the maskrcnn_benchmark dir in it ,




| |
王程
|
|
邮箱：allenwangcheng@163.com
|

签名由 网易邮箱大师 定制

On 07/19/2019 18:59, Tian Zhi wrote:

@allenwangcheng Are you sure you install the project correctly?

**Comment by tianzhi0549** [comment]
@allenwangcheng Please try to reinstall it with the instruction in https://github.com/tianzhi0549/FCOS/blob/master/INSTALL.md.

**Comment by allenwangcheng** [comment]
> @allenwangcheng Please try to reinstall it with the instruction in https://github.com/tianzhi0549/FCOS/blob/master/INSTALL.md.

I reinstall it with the insttuction in https://github.com/tianzhi0549/FCOS/blob/master/INSTALL.md,but when  i run the demo code,error happens ，ImportError: /root/usr/FCOS/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by tianzhi0549** [comment]
@allenwangcheng Please `build` and `_C.cpython-36m-x86_64-linux-gnu.so` and recomplie.

**Comment by allenwangcheng** [comment]
> @allenwangcheng Please remove `build` and `_C.cpython-36m-x86_64-linux-gnu.so` and recomplie.
I rebuild it follow your instruction,but this error still the same....

**Comment by allenwangcheng** [comment]
> @allenwangcheng Please remove `build` and `_C.cpython-36m-x86_64-linux-gnu.so` and recomplie.

i rebuld it by your instruction,but the error still exist

**Comment by allenwangcheng** [comment]
@

**Comment by tianzhi0549** [comment]
@allenwangcheng Can you try to clone the repo again?

**Comment by allenwangcheng** [comment]
ok




| |
王程
|
|
邮箱：allenwangcheng@163.com
|

签名由 网易邮箱大师 定制

On 07/22/2019 11:27, Tian Zhi wrote:

@allenwangcheng Can you try to clone the repo again?

**Comment by allenwangcheng** [comment]
@tianzhi0549 ，thank you so much ,clone repo again just deal with the problem ...amazing...

**Comment by tianzhi0549** [comment]
@allenwangcheng You are welcome.
