### ISSUE TITLE
Did you freeze parts of the backbone when training?

### ISSUE THREAD

**Issue by ZhengMengbin** [tianzhi0549/FCOS#99]
I see MODEL.BACKBONE.FREEZE_CONV_BODY_AT = 2 in the defaults.py, so did you freeze parts of the backbone when training?
![image](https://user-images.githubusercontent.com/26650043/61687417-f3c2d180-ad54-11e9-85fa-a7a7e0dc0dba.png)

**Comment by tianzhi0549** [comment]
@ZhengMengbin Yes. Some layers are frozen.

**Comment by ZhengMengbin** [comment]
Thanks for your reply!
